### PR TITLE
Add qoutes when installing local tgz to fix spacing in the file path

### PR DESCRIPTION
**Pull request by A-Ghorab**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes
The pull request is to fix an issue with installing local Tarball files that have spaces in the file path. When attempting to install a package with a file path containing spaces, such as "C:\ProgramData\Node-Red Installer\nodes\objectif-lune-node-red-contrib-package.tgz", the installation would fail with an error message indicating the path was trimmed, like this:

"ERR! path C:\ProgramData\Node-Red/package.json"

The root cause is that the npm install command was not properly handling the file path with spaces, and as a result, the path was being truncated. also in the logs it have this npm install command 

npm.cmd install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict C:\ProgramData\Node-Red Installer\nodes\objectif-lune-node-red-contrib-package.tgz

The fix is to include double quotes around the file path in the npm install command, like this:

npm.cmd install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict "C:\ProgramData\Node-Red Installer\nodes\objectif-lune-node-red-contrib-package.tgz"

By wrapping the file path in double quotes, the npm install command can properly handle the spaces in the path and successfully install the local Tarball file.

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `npm run test` to verify the unit tests pass
- [x] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
Hi @A-Ghorab thanks for the contribution. Please sign the EasyCLA (as mentioned above) so that we can run tests and review.

**Comment by A-Ghorab** [comment]
> Hi @A-Ghorab thanks for the contribution. Please sign the EasyCLA (as mentioned above) so that we can run tests and review.

Sure, I'm contacting my employer to get it signed, Thanks

**Comment by rmpasswd** [comment]
Hello,
This issue also affects those who have space in their windows user name. Kindly run the tests and review and update.
image

**Comment by A-Ghorab** [comment]
duo to a request from my employer, i create a new pull request https://github.com/node-red/node-red/pull/4949, so this one will be closed

**Pull request closed without merging**
