### PR TITLE
Fix invisible icons in IE

### PR DESCRIPTION
**Pull request by kazuhitoyokoi**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes
Currently, nodes in the workspace have no icon in IE 11 browser as the following screenshot.

image

This problem occurred because IE cannot obtain width and height from an SVG file. When the Node-RED flow editor shows SVG icons, size adjustment is not needed because SVG is a vector format. Therefore, I added the handling to avoid size adjustment.

## Checklist
- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by knolleary** [comment]
What does this mean for the svg icons other people may create?

What should the docs say in terms of width/height viewbox etc?

**Comment by dceejay** [comment]
Does this fix only affect IE11 users ? IF someone creates an icon 200x300 (or more likely doesn't bother to rescale an existing one) - will it still behave ?

**Comment by kazuhitoyokoi** [comment]
@knolleary @dceejay Yes, this fix is for IE only. On Chrome, Firefox and IE on Windows 10, I checked that there's no problem when icon size is larger than 60 x 40. (I didn't checked it on Safari on Mac.)
To avoid the same trouble on IE, I think that the document about `width`, `height` and `viewBox` will be useful.

**Comment by kazuhitoyokoi** [comment]
Thank you! This fix will be good for enterprise users.

**Pull request merged**
