### PR TITLE
fixing minor typo in node's documentation

### PR DESCRIPTION
**Pull request by matthiasradde**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

Fixed typo in documentation.

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by matthiasradde** [comment]
strange: I have signed the Contributor License Agreement, but it is not checked here.

**Comment by hardillb** [comment]
The commit was not made with an email address that is linked to your github account.
The commit was from your `...meule.com` address and github only knows your `gmx.net` address.

You have 3 options

 1. add the other address to your github account
 2. resubmit a new pull request with the commit done with your `gmx.net` address 
 3. edit the email address linked to the  commit on your machine and force push the change to your fork and it should update this pull request.

Options 1 & 2 are probably easiest

**Comment by matthiasradde** [comment]
Thank you - forgot that I created the commit with my bussins-email-account.
I've added the ...meule.com-email-address to my github-account - hopefully it is working now. Otherwise I will try the other options.

**Comment by dceejay** [comment]
thanks

**Pull request merged**
