### PR TITLE
Add pinned tab icon for Safari

### PR DESCRIPTION
**Pull request by natcl**
This adds a pinned tab icon for Safari, see this page for more info:
https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html

Thanks !

### CODE REVIEW

**Comment by natcl** [comment]
Please santa, for 0.14 ? ;)

**Comment by knolleary** [comment]
node-red-gitbot:  please check the cla status.

**Comment by knolleary** [comment]
I cannot figure out how pinning tabs works in Safari. Everything I've read suggests you just drag the tab to the left, or your right click to get a 'pin tab' menu option. Neither work for me, on Safari 9.1.1. I must be missing something obvious...

**Comment by natcl** [comment]
Right click on the tab and select pin tab ?

**Comment by natcl** [comment]
Here's how I do it (in french...)
Safari 9.1.1
img

**Comment by knolleary** [comment]
Really odd - I don't get the option in that menu to pin a tab.

**Comment by natcl** [comment]
Ahh are you in private browsing mode ? Pins don't work in that mode...

**Comment by dceejay** [comment]
Nick - works for me - Pin Tab - so can review on Monday.
image

**Comment by knolleary** [comment]
Appears to be El Capitan only - I've not clicked the update from Yosemite yet... really should get around to that.

**Comment by hardillb** [comment]
Tab pinning works on Chrome (and Firefox) as well so we can test them all

**Comment by dceejay** [comment]
Thanks @natcl

**Pull request merged**
