### PR TITLE
update settings comments to describe how to setup for ipv6

### LINKED ISSUE #1674: IPv6
### What are the steps to reproduce?
Clone, `npm install` and `npm start`

### What happens?
Server don't lisents to IPv6 address

### What do you expect to happen?
To lisent IPv6 address

### Please tell us about your environment:

- [x] Node-RED version: 0.18.3
- [x] node.js version: 9.3
- [x] npm version: 5.6
- [x] Platform/OS: Win10
- [x] Browser: Chrome 63

### PR DESCRIPTION
**Pull request by dceejay**
to close #1674

### CODE REVIEW

**Comment by knolleary** [comment]
Should we update the `uiHost` setting, or at least comment, in https://github.com/node-red/node-red/blob/master/settings.js#L28 to mention ipv6 option?

**Comment by dceejay** [comment]
so maybe add comment for  ::1  for ipv6 loopback only ?

**Comment by knolleary** [comment]
I'm not familiar with ipv6 enough, so will leave the details to you 😉 .. but I do think we should have something about ipv6 in the settings file comment.

**Comment by hardillb** [comment]
I'd be tempted to leave it as it is binding to IPv4 and just document how to change it in the settings file to enable IPv6.

Some Linux distros still ship with IPv6 disabled by default (The internal distro used to) so I think this would fail to start on those machines

**Comment by knolleary** [comment]
@hardillb good point - that would be a bad thing.

**Comment by dceejay** [comment]
OK will check that... before proceeding

**Comment by dceejay** [comment]
So far working by default on OSX, Win7, Win10, Raspbian Stretch, Ubuntu 16.04.
Also working if I kill ipv6 on Raspbian, Ubuntu 16.04.

**Comment by knolleary** [comment]
From the [node.js docs](https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback):

> Note: In most operating systems, listening to the unspecified IPv6 address (::) may cause the net.Server to also listen on the unspecified IPv4 address (0.0.0.0).

I am nervous about the 'in most' statement - as in, this isn't a guaranteed behaviour.

**Pull request merged**
