### PR TITLE
Monaco-0-49-0

### PR DESCRIPTION
**Pull request by Steve-Mcl**
## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Vendor update

## Proposed changes

Updates monaco to latest V0.49.0

https://github.com/node-red/nr-monaco-build/releases/tag/0.49.0

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ ] I have run `npm run test` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by FabsMuller** [comment]
Stephen, I sent you a pvt on NR forum.

**Comment by knolleary** [comment]
@Steve-Mcl does this correspond to a tagged release on https://github.com/node-red/nr-monaco-build ? I'd prefer that we are able to point to a tag on that repo when copying files over so we have a clear sense of their pedigree.

**Comment by Steve-Mcl** [comment]
> @Steve-Mcl does this correspond to a tagged release on https://github.com/node-red/nr-monaco-build ? I'd prefer that we are able to point to a tag on that repo when copying files over so we have a clear sense of their pedigree.

No, but it _does_ relate to the branch https://github.com/node-red/nr-monaco-build/tree/update-for-v4 

We could merge and tag that first if need be?

**Comment by knolleary** [comment]
I have merged and tagged the changes in the monaco repo. This PR syncs the changes from https://github.com/node-red/nr-monaco-build/releases/tag/0.49.0 into the NR repo

**Pull request merged**
