### PR TITLE
get port from environment by default

### PR DESCRIPTION
**Pull request by mastertinner**
This allows the app to run on modern cloud platforms like [Cloud Foundry](https://www.cloudfoundry.org) without having any effect on other users. It might even be suitable to configure all the other variables through the environment by default and only taking the value from the `settings.js` file if there is no respective environment variable. This allows for a more modern and flexible way to deploy the application as described in this article: [http://12factor.net/config](http://12factor.net/config).

### CODE REVIEW

**Comment by mastertinner** [comment]
If you guys think it's a good idea and that it should be merged, I'll sign the CLA asap ;-)

**Comment by dceejay** [comment]
it's a well known technique - we use that on the bluemix version here - https://github.com/node-red/node-red-bluemix-starter/blob/master/bluemix-settings.js. Not sure if we want just PORT as the variable as that may be too generic a choice that may be in use already.

**Comment by knolleary** [comment]
I think it ought to be PORT as that is the well known property to use for
exactly this scenario.

But I think it needs holding until 0.14.0 where we can draw attention to it
in the release notes just in case anyone is running with PORT set but
currently ignored.

**Comment by mastertinner** [comment]
I would agree with @knolleary. PORT is quite the standard in my opinion. So would you like me to keep the PR up to date or make a new one as soon as you guys are ready?

**Comment by dceejay** [comment]
I have no problem as long as it is the de-facto standard. Up to you. As it's a tiny change we are happy to apply it manually if you like.

**Comment by mastertinner** [comment]
Ok, thanks @dceejay! In that case i'll close the PR.

**Pull request closed without merging**
