### PR TITLE
Improvements to DE translation

### PR DESCRIPTION
**Pull request by matthiasradde**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

Update/add documentation for De locale

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality (not needed :-) )

### CODE REVIEW

**Comment by knolleary** [comment]
How does this relate to #2806?

**Comment by matthiasradde** [comment]
Both PR are about german translation.
This #2851 is only about some typos in documentation for some nodes and add the missing translation for the "Complete"-node.
The #2806 seems to for fixing a lot more typos/translation-issues.

As I am not used to work in/contribute to large OpenSource-projects I might do things not the way I should do (because I don't know better). So please be tolerant and teach me how to do it better - Thank you :-)

**Comment by heikokue** [comment]
Hello Matthias, nice to hear from you and your engagement to improve the german translation.
I reviewed your PR and as I saw, the changes are already covered by my PR #2806.
I just finished and pushed my translations and would really happy for each review and feedback.
Thanks and stay healthy! Heiko

**Comment by heikokue** [comment]
@knolleary @dceejay This PR is already contained in #2806 and can be closed.
@matthiasradde Can you please review #2806 after next release?

**Comment by dceejay** [comment]
closing as requested

**Pull request closed without merging**
