### PR TITLE
Delay node enhancements

### PR DESCRIPTION
**Pull request by kazuhitoyokoi**
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes
I added the code to support msg.rate and nodeMessageBufferMaxLength in the delay node. I suggested these functionalities in the [design note](https://github.com/node-red/designs/pull/12) and the [discussion slides](https://github.com/node-red-hitachi/node-red-notes/blob/master/Teleconference/20190604/20190604nodered_teleconference_yokoi.pptx).

## Checklist
- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [x] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by knolleary** [comment]
@kazuhitoyokoi Are we expecting an update on this PR today? I am waiting to do the 1.3 beta release, but if there isn't going to be an update soon, then I want to get the beta released and this PR can be merged afterwards.

**Comment by kazuhitoyokoi** [comment]
@knolleary It's ready to merge. I'm just going to update 89-delay.html file to add documentation about msg.rate.

**Comment by dceejay** [comment]
@knolleary - may want to tweak the setting property name - currently `nodeMessageBufferMaxLength` as it doesn't really say what it does to which node.

**Comment by knolleary** [comment]
@dceejay that is a common property used by lots of the core nodes that buffer messages.

**Comment by dceejay** [comment]
ah ok - makes sense in that case :-)

**Comment by kazuhitoyokoi** [comment]
@knolleary @dceejay I updated the HTML file of the delay node. Could you check it after or before the beta release?

**Comment by kazuhitoyokoi** [comment]
> One question - as this node can work across multiple topics - is the queue depth a total size of queued objects across all topics ? or per topic ? (I don't mind just asking - as should probably be noted in docs )

@dceejay In this implementation, the queue is single across all topics.

**Comment by dceejay** [comment]
My slight concern is that when in delay mode we have e specific option to say let `msg.delay` override the delay. Now for the rate limit mode we are saying let any `msg.rate` message change the rate. (and that then applies from then on unless changed again)

**Comment by knolleary** [comment]
@dceejay I think that is a very valid concern.

If the user can choose to use `msg.delay` in the node, but has no choice about `msg.rate`, then the node is not consistent. Unless you convince me otherwise, I think there needs to be an option in the node to allow msg.rate be used.

Given the discussion is not finished on this, I'm going to publish 1.3-beta.1 without this PR. There is still plenty of time to get this PR merged for the final release of 1.3.0, but I don't want to delay the beta any more.

**Comment by kazuhitoyokoi** [comment]
@dceejay Thank you!

**Comment by dceejay** [comment]
We still need to resolve the difference in behaviour from delay and rate limit modes.

Currently on delay side - you have to select to enable the msg.delay override and it is on a per message basis - so the next msg without a delay property will default back to the configured time. In this rate implementation:
 1) msg.rate will always override the existing setting and will set it from then on until changed again.
 2) only sets it for all topics mode - doesn't affect the per topic modes (queue and timed).

**Comment by kazuhitoyokoi** [comment]
I see. I thought that the checkbox for "allow rate override" may be more natural instead of the item on the pull-down menu.

**Comment by dceejay** [comment]
Well it may be if it also affected all rate options - currently you only change the all messages one.

**Comment by kazuhitoyokoi** [comment]
Thank you for the explanation. I found that the pull-down menu is easy to understand for users.

**Comment by dceejay** [comment]
Actually thinking about it - I think you are right - adding the option to the other modes would be more consistent. I will add a checkbox instead - and add to the other modes.

**Comment by dceejay** [comment]
OK - all pushed to that branch - would appreciate if you can take a look. Thanks

**Pull request merged**
