### PR TITLE
tcp node: queue pending messages while connecting to tcp server

### PR DESCRIPTION
**Pull request by boneskull**
- [x] Bugfix (non-breaking change which fixes an issue)

## Proposed changes

- queues messages on a per-client basis while waiting for TCP server connection
- add [`denque`](https://npm.im/denque) package for performance
- add tests
- remove a duplicate test in `31-tcp_request.spec.js`

This code uses ES6 conventions allowed in Node.js v4.x (the tests pass on this version).

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [x] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by boneskull** [comment]
`denque` is here for performance reasons (`shift` happens in constant time, but with an `Array` it's linear).  

But it occurs to me that, in the event of an unresponsive server, messages will be queued indefinitely.  This means at some point we need to start dropping messages.  There are a couple ways to do that, but the most straightforward could just be to check the size after a `push()`, then if it's bigger than *n*, `shift()` off into the ether.  let's say *n* = 1000, for lack of a better place to start.

**Comment by boneskull** [comment]
I should probably add a test for the queue size.

**Comment by boneskull** [comment]
all of this passes locally..hm..

**Comment by knolleary** [comment]
@boneskull 

> 1) trigger node should be able to extend the delay (but with no 2nd output):

appears to be failing on node 8 quiet regularly. We won't hold it against you.

**Comment by dceejay** [comment]
drat - I had a go a fixing the following test as that was also failing... didn't spot this failng also...

**Comment by dceejay** [comment]
looks good to me - I'm happy to say merge.

**Pull request merged**
