### PR TITLE
exec: report PID to kill this exact process later

### PR DESCRIPTION
**Pull request by dvv**
## Before you hit that Submit button....

Please read our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
before submitting a pull-request.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

If you want to raise a pull-request with a new feature, or a refactoring
of existing code, it **may well get rejected** if it hasn't been discussed on
the [mailing list](https://groups.google.com/forum/#!forum/node-red) or
[slack team](https://nodered.org/slack) first.

## Proposed changes

Describe the nature of this change. What problem does it address?

EXEC node has got ability to kill running process by PID but the PID is unknown when the process is started.
Provided the patch which reports spawned process PID via third output in the form `{pid: PID}`. The subscriber may hold PID in, say, `context.flow` to later kill _this exact_ process.

## Checklist
_Put an `x` in the boxes that apply_

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by dceejay** [comment]
The PID is already provided via the status 
https://github.com/node-red/node-red/blob/master/nodes/core/core/75-exec.js#L77
so can already be seen by using the `status` node ...

**Comment by dvv** [comment]
@dceejay It's seen by eyes but how to get it into, say, function node logic?

**Comment by dceejay** [comment]
image

**Comment by dvv** [comment]
Great! The rest is to tie the status to the original message which comes to exec node input. Is it possible?

**Comment by dceejay** [comment]
Yes, plenty of ways, join node, using flow (or global context), which is why we suggest the mailing list and slack channel, so everyone can help. Have to head out. good luck

**Comment by knolleary** [comment]
Closing as this as it can be addressed using the Status node. If you want to discuss further, please follow up on Slack or Mailing List.

**Comment by dvv** [comment]
I believe exec node is not suited for my way of extensive reuse as to glue source message and status may be not an 1-to-1 map.

**Pull request closed without merging**
