### PR TITLE
Fix basic auth with empty username or password

### LINKED ISSUE #3324: HTTP-request node fails to authenticate when username or password is empty
### Current Behavior

Basic Auth should base64 encode `username:password` but if either is empty then `undefined:password` or `username:undefined` ends up getting encoded.

### Expected Behavior

It should encode an empty string e.g. `:password` or `username:`

### Steps To Reproduce

- Tick the use Authentication checkbox
- Select basic auth
- Leave either the username or password blank

Also fails is `username:password@` is prepended to the hostname in the URL

### Example flow

```
[{"id":"f80df7c4fb6a5584","type":"inject","z":"706f8b78.caf304","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":300,"y":500,"wires":[["56c4fdb246ef2d5e"]]},{"id":"56c4fdb246ef2d5e","type":"http request","z":"706f8b78.caf304","name":"sep creds","method":"GET","ret":"txt","paytoqs":"ignore","url":"http://localhost:1880/auth","tls":"","persist":false,"proxy":"","authType":"basic","senderr":false,"x":440,"y":500,"wires":[["9b07e810c11fc9e8"]]},{"id":"9b07e810c11fc9e8","type":"debug","z":"706f8b78.caf304","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":650,"y":420,"wires":[]},{"id":"4047bb86ad0fb45f","type":"http in","z":"706f8b78.caf304","name":"","url":"/auth","method":"get","upload":false,"swaggerDoc":"","x":240,"y":600,"wires":[["408e1f651236e5c5","70dee9f832296095"]]},{"id":"408e1f651236e5c5","type":"http response","z":"706f8b78.caf304","name":"","statusCode":"","headers":{},"x":440,"y":560,"wires":[]},{"id":"4adc6a1176b21712","type":"debug","z":"706f8b78.caf304","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":800,"y":640,"wires":[]},{"id":"d2a860adbda159bb","type":"inject","z":"706f8b78.caf304","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":300,"y":440,"wires":[["3d9dc828cc280ee6"]]},{"id":"3d9dc828cc280ee6","type":"http request","z":"706f8b78.caf304","name":"inline creds","method":"GET","ret":"txt","paytoqs":"ignore","url":"http://:foo@localhost:1880/auth","tls":"","persist":false,"proxy":"","authType":"basic","senderr":false,"x":450,"y":440,"wires":[["9b07e810c11fc9e8"]]},{"id":"40df7def57faddde","type":"base64","z":"706f8b78.caf304","name":"","action":"","property":"payload","x":650,"y":640,"wires":[["4adc6a1176b21712"]]},{"id":"70dee9f832296095","type":"change","z":"706f8b78.caf304","name":"","rules":[{"t":"move","p":"req.rawHeaders[3]","pt":"msg","to":"payload","tot":"msg"},{"t":"set","p":"payload","pt":"msg","to":"$split(payload, \" \")[1]","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":440,"y":620,"wires":[["40df7def57faddde","7e3e5061c605dc56"]]},{"id":"7e3e5061c605dc56","type":"debug","z":"706f8b78.caf304","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":660,"y":580,"wires":[]},{"id":"b5fe1ffc04185c98","type":"inject","z":"706f8b78.caf304","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":300,"y":380,"wires":[["54c7baa412cff821"]]},{"id":"54c7baa412cff821","type":"http request","z":"706f8b78.caf304","name":"sep creds","method":"GET","ret":"txt","paytoqs":"ignore","url":"http://localhost:1880/auth","tls":"","persist":false,"proxy":"","authType":"basic","senderr":false,"x":440,"y":380,"wires":[["9b07e810c11fc9e8"]]},{"id":"5d091b403c2d9410","type":"inject","z":"706f8b78.caf304","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":300,"y":320,"wires":[["67f4d4f2cdfb2e71"]]},{"id":"67f4d4f2cdfb2e71","type":"http request","z":"706f8b78.caf304","name":"inline creds","method":"GET","ret":"txt","paytoqs":"ignore","url":"http://bar:@localhost:1880/auth","tls":"","persist":false,"proxy":"","authType":"","senderr":false,"x":450,"y":320,"wires":[["9b07e810c11fc9e8"]]}]
```

### Environment

- Node-RED version: v2.1.4
- Node.js version: v16.13.1
- npm version: 8.1.2
- Platform/OS: Linux
- Browser: Firefox

### PR DESCRIPTION
**Pull request by hardillb**
fixes #3324

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

Add check for `undefined` values and replace with empty string

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by dceejay** [comment]
looks sensible to me.

**Comment by tobiasoort** [comment]
`undefined` is falsey in JS, so if both are undefined this if would be skipped. Afaik it's valid to only have b64(":") as a basic auth cred (`Og==`). I think that's still not possible to achieve with this fix in place.

**Comment by hardillb** [comment]
Nah, that's and edge case too far and basically pointless. Anybody depending on that behaviour deserves to have it fail.

**Comment by tobiasoort** [comment]
First to be very clear: I very much agree with you. People playing with basic-auth with no actual credentials are screwed anyway - we don't have to support them :) This is more of an interesting discussion for me. If you feel at any moment irritated or tired by me, let me know. I would not let this point stop this PR from getting merged.

I just wonder what that `if` is trying to prevent - you _either_ enter a username _or_ a password _or_ both? Why? Also, Is that clear from the UX that that's the only valid input? 

I prefer no code over 'what is that actually doing here' code.

**Comment by hardillb** [comment]
We need the if because we can't be 100% sure what else is in the `credentials` object, all we know is that it has 1 or more properties. Also it may hold other authentication methods, either now or in the future.

**Pull request merged**
