### PR TITLE
fix : Invalid label for attribute on the tray

### PR DESCRIPTION
**Pull request by DarshanDixit05**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

The label had an invalid "for" attribute which caused the issue in Chrome dev tools, this fix has the appropriate value for the required attribute.

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
Hi, thanks for the contribution. can you please remove package_lock - we dont merge that.

(note to self, we should raise a PR to exclude the package log in .gitignore file)

**Comment by DarshanDixit05** [comment]
Sure

**Comment by DarshanDixit05** [comment]
No I wasn't aware , can you please let me know about the signing process?

**Comment by DarshanDixit05** [comment]
I signed the cla.

**Pull request merged**
