### PR TITLE
Add setting to cause insecure redirect

### PR DESCRIPTION
**Pull request by slaupster**
Add a setting to cause the redirection of insecure HTTP connections to editor to secure HTTPS connections.  Possibly only ever useful behind a proxy, like Bluemix.

### CODE REVIEW

**Comment by knolleary** [comment]
Thanks @slaupster, this has been on my todo list for a while. Not sure `insecureRedirect` is quite the right name for the property... but don't have a better suggestion right now. Once you get the CLA signed (see comment from @jsf-clabot above), we can get this merged. Just note we *may* change the property name.

**Comment by slaupster** [comment]
@knolleary - no worries, done cla... thanks

**Comment by knolleary** [comment]
Thanks 👍

**Comment by knolleary** [comment]
For completeness, have renamed the property `requireHttps`.

**Comment by slaupster** [comment]
thanks @knolleary - any idea when this will show up in npm ?

**Comment by knolleary** [comment]
@slaupster unless we end up doing a 0.15.x maintenance release for something urgent (not current plans), then it will be in 0.16 which will be this side of Xmas.

**Pull request merged**
