### PR TITLE
Fixes: #4650. Name field of all core nodes placed at first

### PR DESCRIPTION
**Pull request by debarkamondal**
## Types of changes

What types of changes does your code introduce?
Put an `x` in the boxes that apply
-->

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes
 To bring uniformity to the placement of the 'name' field of core nodes in input forms.

Readjusts the HTML code to bring the 'name' input field to the top of every core node.

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `npm run test` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by dceejay** [comment]
Hi, thanks for this. Have you seen #4656 that covers the same ground and also adds the ability to set the in or out property as appropriate ?

**Comment by debarkamondal** [comment]
> Hi, thanks for this. Have you seen #4656 that covers the same ground and also adds the ability to set the in or out property as appropriate ?

Sorry for the inconvenience I will close the pull request

**Comment by debarkamondal** [comment]
Closing this pull request as issue #4656 already fixes #4673 and more.

**Comment by dceejay** [comment]
Not an inconvenience at all - Thanks for creating the PR - though asking first would have saved you some effort :-) 
Probably worth checking if #4656 does cover all the nodes.
(And there are node-red-nodes that need looking at also ;-)

**Pull request closed without merging**
