### PR TITLE
Drop eol node 14 & 16

### PR DESCRIPTION
**Pull request by Rotzbua**
- [x] Bugfix
- [x] Breaking
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

Node 16 is EOL in one week: September 11th, 2023
https://nodejs.org/en/blog/announcements/nodejs16-eol

Includes #4306:
Node 14 was removed from test matrix. #4084
Since it is not tested anymore it should not be allowed to run on these version.

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by knolleary** [comment]
We do not plan to drop Node 16 until the Node-RED 4.x stream as per our support statement - https://nodered.org/about/releases/

We have fallen behind in our scheduling of our releases, but we'll keep Node 16 in the matrix *for now*.

**Comment by Rotzbua** [comment]
@knolleary thanks for the statement.

I think the link to release plan would be useful in the `CONTRIBUTING.md`?

The release plan states:

> At the end of April 2023, when Node 14.x reaches its end-of-life, we will publish Node-RED 4.x that will drop support for Node 14.

But currently drop of node 14 would be with release 3.1.

Maybe revert removal of node 14 with #4084 for release 3.1 to comply with release plan?
And since releases behind schedule make nodered 4.0 dropping node 14 & 16?

**Comment by knolleary** [comment]
We are reviewing our plans around the release schedule. The focus right now is to get 3.1 released - we aren't making any additional changes to the node.js support in that release beyond what we already have. Once we get that done, we'll shift focus to 4.x and make the necessary updates to the code and test matrix.

**Comment by knolleary** [comment]
Superseded by https://github.com/node-red/node-red/pull/4571

**Pull request closed without merging**
