### PR TITLE
html entities should be entered in http request node (bug 1024)

### PR DESCRIPTION
**Pull request by wajnberg**
Signed-off-by: Moshe Wajnberg <wajnberg@il.ibm.com>

### CODE REVIEW

**Comment by wajnberg** [comment]
Hello @knolleary ,

It's the pull request we mention today
Thank you for handling this

And once more all my apologizes

Best Regards

**Comment by knolleary** [comment]
This has fixed the very specific cases mentioned in #1024, but doesn't address them generally.

I can now include `&param` in the url fields without it being modified, but I cannot include it in the file path fields.

I can now include `<b>Hi</b>` in the file path fields, but I cannot include it in the url fields.

HTML entities *must* be handled properly in *all* fields.

**Comment by knolleary** [comment]
Three tests producing unexpected results.

## Test case 1: `filepath`

Tested the `file in` node with two filenames:
   - `/home/nol/my_<file>.txt`
   - `/home/nol/my_<file>`

With text direction set to Left-to-Right, the node label appears as:

nr-file-label-ltr

With text direction set to Right-to-Left, the node label appears as:

nr-file-label-rtl

In the first node, the `/` has moved to the right but nothing else has changed.
In the second node an extra `<` has appeared at the left, the `>` has disappeared and the `/` has moved to the right.

In both cases (LTR and RTL), the edit form input doesn't change:

nr-file-input-ltr

nr-file-input-2-ltr

The text remains left-aligned regardless of text direction.

## Test case 2: `url`

Tested the `http in` node with the path `/test/path?a=1&param=<b>&ts=123`

Text direction L-to-R:

nr-http-label-ltr

Text direction R-to-L:

nr-http-label-rtl

## Test case 3: 'normal' fields

Tested a 'regular' `<input>` for a normal (non-bidi) field with two strings. In this instance, the `name` field of `file in`.
 - `this is <b>`
 - `this is <b> test`

L-to-R:

nr-name-ltr
nr-name-2-ltr

R-to-L:
nr-name-rtl
nr-name-2-rtl

If the text ends with `>` (first test case), it disappears, new `<` appears at start. If the text doesn't end with `>` (second test case), it is displayed correctly.

Note in both cases, when set R-to-L, the text is right-aligned.

**Comment by knolleary** [comment]
Superseded by #1041

**Pull request closed without merging**
