### PR TITLE
fix tooltip language in subflow

### PR DESCRIPTION
**Pull request by piyonakajima**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes
Because the tooltip language in customUI of subflow was "en-US","ja","de"...,
I modified them to become "English", "Japanese", "German".
I also changed the width 50px to 120px, because "Chinese(Simplified)" overwrapped with Label area.

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by knolleary** [comment]
Hi - thanks for raising this.

The choice of using the language codes was intentional to keep it compact, so this is a design change rather than a bug-fix.

Can you explain why you think it should have the full language name?

**Comment by piyonakajima** [comment]
Because User Setting and the bottom of the properties  are written  by the full language name, 
I think it is better that this tooltip is also written by the full language name,
I think the same expression is good for user experience.
(I signed CLA yesterday after PR, I’m sorry.)

**Comment by kazuhitoyokoi** [comment]
I think that beginner Node-RED users aren't familiar with language code. In my opinion, the compact tooltip looks good but it's better to use full language names which are same as bottom menu.

**Comment by piyonakajima** [comment]
I signed CLA but email address was diffrent from when I commited. I fixed it.

**Pull request merged**
