### PR TITLE
Dynamic link call

### LINKED ISSUE #3404: Link call doesn't work inside subflow
### Current Behavior

A link call outside a subflow works as expected. Placing that same link call inside a subflow makes it time out and not do anything. See example in 'Steps To Reproduce'.

### Expected Behavior

I would expect a link call to behave exactly the same inside a subflow as it does in a regular flow.
If this behavior is by design, I would at least expect an error to come up that mentions that a link call doesn't work inside a subflow. 

### Steps To Reproduce

See example:
```
[{"id":"eba3f6f1ec133a59","type":"subflow","name":"Subflow 1","info":"","in":[{"x":80,"y":80,"wires":[{"id":"aa62622a2b62fd65"}]}],"out":[]},{"id":"aa62622a2b62fd65","type":"link call","z":"eba3f6f1ec133a59","name":"","links":["11289a75e4ad5fca"],"timeout":"30","x":200,"y":80,"wires":[["2dd0b7b623e38c85"]]},{"id":"2dd0b7b623e38c85","type":"debug","z":"eba3f6f1ec133a59","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":330,"y":80,"wires":[]},{"id":"11289a75e4ad5fca","type":"link in","z":"eba3f6f1ec133a59","name":"test in","links":[],"x":215,"y":220,"wires":[["c8c90c89df0e8294","89f82393194c0202"]]},{"id":"c8c90c89df0e8294","type":"link out","z":"eba3f6f1ec133a59","name":"","mode":"return","links":[],"x":305,"y":220,"wires":[]},{"id":"89f82393194c0202","type":"debug","z":"eba3f6f1ec133a59","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":340,"y":180,"wires":[]},{"id":"75e3bc6be36d21a2","type":"inject","z":"b88d0ccd9c6c63d6","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":650,"y":380,"wires":[["fa6ec1460912454b"]]},{"id":"fa6ec1460912454b","type":"link call","z":"b88d0ccd9c6c63d6","name":"","links":["5af86a1f95f37aff"],"timeout":"30","x":790,"y":380,"wires":[["eb51ce6970fa1df9"]]},{"id":"eb51ce6970fa1df9","type":"debug","z":"b88d0ccd9c6c63d6","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":920,"y":380,"wires":[]},{"id":"5af86a1f95f37aff","type":"link in","z":"b88d0ccd9c6c63d6","name":"test in","links":[],"x":805,"y":520,"wires":[["92fb9ee5c7624fb2","fa9e715dabd6efb9"]]},{"id":"92fb9ee5c7624fb2","type":"link out","z":"b88d0ccd9c6c63d6","name":"","mode":"return","links":[],"x":895,"y":520,"wires":[]},{"id":"fa9e715dabd6efb9","type":"debug","z":"b88d0ccd9c6c63d6","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":930,"y":480,"wires":[]},{"id":"88fc2da08203ac7d","type":"inject","z":"b88d0ccd9c6c63d6","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":660,"y":680,"wires":[["7bbcc883ab5c3eb4"]]},{"id":"7bbcc883ab5c3eb4","type":"subflow:eba3f6f1ec133a59","z":"b88d0ccd9c6c63d6","x":840,"y":680,"wires":[]}]
```

Subflow 1 is created by selecting everything above, except for the inject node. If you want to make sure while testing that the contents are exactly the same, remove the bottom inject node and the subflow, duplicate everything left, select everything except the inject node, and use the convert to subflow action.

Click the inject node that is not connected to the subflow. You get two messages in the debug log, once from inside the link call, once from after it was done.

Click the inject node connected to the subflow. After 30 seconds you get a timeout.

### Example flow

See Steps To Reproduce

### Environment

Docker: nodered/node-red:2.2.0

- Node-RED version: v2.2.0
- Node.js version: v14.18.2
- npm version: 6.14.15
- Platform/OS: Windows 10
- Browser: Vivaldi / Chrome

### LINKED ISSUE #3441: Feature: Dynamic link-call
## Preamble
Following up on the [actionflows issue](https://discourse.nodered.org/t/problem-with-node-red-contrib-actionflows-since-upgrade-to-2-2-0/57368/40) and how it used global context to provide "dynamic subroutine calls" capabilities.

## Description
* Add ability to perform link-call dynamically
* Update documentation

## Considerations / questions
* Should we add a mode selector "Static", "Dynamic" where "Static" mode operates as it does now and "Dynamic" mode would hide the "node selection tree"  
* Would the dynamic call be made by `name` or `id` (or both)?
* What property of `msg` would be used?  
  * `msg.link` ? `msg.linkId` ?   `msg.linkName` ?

## Slack discussion 
https://node-red.slack.com/archives/C9RSU6S56/p1644844378969309

### PR DESCRIPTION
**Pull request by Steve-Mcl**
closes #3441
fixes #3404

## Types of changes
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes

Add dynamic link call as discussed in #3441 

## Checklist
- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [x] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by dceejay** [comment]
If I "migrate" / open an existing link call then the type is blank - the on open should check if it's null and set it to default...

image

**Comment by Steve-Mcl** [comment]
> If I "migrate" / open an existing link call then the type is blank - the onEditPrepare should check if it's null and set it to default

I could have sworn I did that in b665698


> Looking at the UI and possible usability - just wondering if when in dynamic mode the list of nodes to call could still be shown - but not be selectable - IE just a list of the names.... (that you could set msg.target to) ? Would that be helpful ?

That was among the lines of what I was thinking back in my earlier questions. However i believe we can do this without issue in a later iteration. 


I'll fix up the UI bug again.

**Comment by dceejay** [comment]
not sure what indexOf(undefined) would do... is that a well known "trick" ? (not seen that before)

**Comment by Steve-Mcl** [comment]
> not sure what indexOf(undefined) would do... is that a well known "trick" ? (not seen that before).

(for anyone else reading) referring to the line `if (["static","dynamic"].indexOf(this.linkType) < 0) {`

If `this.linkType` is ANYTHING except what we want (in this case "static" or "dynamic"), it will return -1 & therefore get corrected to the default "static"...

image


RE: not initialising, found a copy+paste error - DOH

Will correct this in 2 mins.

**Review by knolleary — APPROVED** [review]

**Pull request merged**
