### PR TITLE
Added cookie parser to the httpIn node and dependencies list

### PR DESCRIPTION
**Pull request by sax1johno**
I had the need for CookieParser so I could create sessions on HTTP nodes.

### CODE REVIEW

**Comment by hardillb** [comment]
Please check the Contributing (https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) file for details of the CLA that needs to be completed before pull requests can be accepted.

It is also preferred that changes should be discussed on the mailing list first to work out any issues that may arise. 

A couple of points about the code change:

 1. This should probably be optional as there could be users dependant on the current lack of session support to ensure each request is a new session.

 2. Your changes to the package.json include the stuff added by npm post install as well as changing the indentation of the entire file, this should be reverted back.

**Comment by sax1johno** [comment]
Hey there,

My apologies - I kinda had my head down and didn't even notice the
"contributions" file until after I submitted the PR.

I'll address the mailing list now for a few pieces that I'd like to add.

I submitted a CLA last night so hopefully that'll come out. I've attached
to his message as well just in case it facilitates things.

Thanks,

John O'Connor

**Comment by sax1johno** [comment]
Updated the package.json file so that it only contains a new dependency on Cookie Parser. 

After discussion in the mailing list it seems like this should have a minimal impact

**Comment by sax1johno** [comment]
Hey guys - I signed the cla a while ago and sent it over but I still haven't been accepted. Is there something else I need to do?

**Comment by knolleary** [comment]
Hi @sax1johno - CLA received and all is good on that front.

You may have spotted I added it to the 'Current' milestone late last-night - so this is definitely on the todo list for our next release.

Whilst I was there, I did a quick review of the changes to see if I could merge, but there were a couple things that held me back. As it was nearing 1am, I closed the tab rather than add comments.

The main issue is `package.json` has had all its whitespace changed - would prefer if it simply added the one new dependency and left the formatting alone.

The other part, which arguably is beyond the scope of this specific PR, is thinking how we provide a message-driven way to set/delete cookies as part of the response - so we don't have to expose the functions on `msg.res`.

If you fix up `package.json`, we can get this merged. If you're interesting in proposing something for the second in a separate thread, then we'd welcome it (but equally, you don't need to feel obliged to, having opened this can of worms).

**Comment by knolleary** [comment]
node-red-gitbot: please update CLA status

**Comment by knolleary** [comment]
Added manually into 0.14.0 branch - including the ability to set/clear cookies using `msg.cookies` passed to the response node - 5f6a0141f056b28f948184213ebab7645dce5c62

**Pull request closed without merging**
