### PR TITLE
Fix a problem of file append test on Windows

### PR DESCRIPTION
**Pull request by Kazuki-Nakanishi**
This is a pull request that was discussed on #1352.
## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

The test script `50-file_spec.js` fails only on Windows environment.
On the Windows environment, the unlinked file won't be completely deleted until its file handle is closed.  Under this condition, to recreate the same file fails. So I explicitly call `close`.

## Checklist
_Put an `x` in the boxes that apply_

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by Kazuki-Nakanishi** [comment]
Although all tests passed on Windows, Ubuntu and mac OS in my environment, they somehow failed on the Travis environment.
Sorry, but please let me investigate it.

**Comment by Kazuki-Nakanishi** [comment]
The reason that this problem occurs only on Linux was that the behavior of `fs-extra` is difference between Windows and Linux.
The following is a sample code to see the difference.

```
var fs = require("fs-extra");
var filename='a.txt';
try { fs.unlinkSync(filename); } catch(e) {}

var wstream = fs.createWriteStream(filename, { flags:'a', autoClose:true }); console.log(fs.statSync(filename).ino);

fs.unlinkSync(filename);
wstream.end(); // comment out this line.
setTimeout(function() {
  fs.writeFileSync(filename,"");
  console.log(fs.statSync(filename).ino);
}, 500);
```

- Windows
  - Run the above code as is: Node.js returns a different inode.
  - Run with commenting out `wstream.end();`: An error occurs. (This is the case of an original problem.)

- Linux
  - Run the above code as is: Node.js returns a same inode. (This is the case that causes a Travis error.)
  - Run with commenting out `wstream.end();`: Node.js returns a different inode.

---
I thought that `close` function in a Node-RED node might be called from somewhere. But I've reconsidered that `close` function is called only when Node-RED instance stops. If this is true, I should not call `close` directly. And it means that this test case cannot be run on Windows. In conclusion, I just simply skip this test case when running on Windows.
If my understanding is not correct, please let me know.

**Comment by knolleary** [comment]
Need to check what impact this difference in behaviour has on the functionality of the node. Don't want to disable the test if it will hide a bug

**Comment by Kazuki-Nakanishi** [comment]
@knolleary
Thank you for your comment!
Let me organize whether the difference impacts the Node-RED behavior or not.

- `Run the above code as is`:
Even if the file that is being appended some strings by a file node was deleted from the other process, the file node does not close the file handle. At the time, when the other process creates a new file with the same filename, new inode is always assigned to the file. So the problem of Linux does not actually occur.

- `Run with commenting out wstream.end()`
After a file node appends strings to a file, if the other process tries to open the file, an error occurs.
As the message is like "file is locked", the other process can recognize that the file cannot be modified.
With regard to a file node itself, this problem should not happen because a file node always calls `wstream.end();` when necessary.

---
I found that the behavior is different between `del` command and deleting a file on Windows explorer (GUI).

- `del` command
1-1. Append strings to `a.txt` with a file node.
1-2. Run `del a.txt` on command prompt. (or `fs.unlink` on Node.js)
1-3. Run `echo abc > a.txt` on command prompt.
Then `Access is denied.` error occurs.

- deleting a file on Windows explorer
2-1. Append strings to `a.txt` with a file node.
2-2. Delete `a.txt` on Windows explorer.
2-3. Create `a.txt` on Windows explorer.
2-4. Append strings to `a.txt` with a file node.
This case works fine.

When 2-2 has done, a temporary file whose file size is same as `a.txt` is shown on explorer.
I assumed that the file is renamed from `a.txt` (although this file actually cannot be opened).



Based on this information, I changed a test sequence from `unlink` to `rename and unlink`, then the test passed without error on both Windows 8.1 and Windows 10.
I think that this is the correct test sequence for deleting a file on Windows explorer.

**Comment by knolleary** [comment]
Great - thanks for investigating that.

**Pull request merged**
