### PR TITLE
update getObjectProperty(msg,expr)

### PR DESCRIPTION
**Pull request by abruno06**
update getObjectProperty(msg,expr) to support invalid expression to return undefined instead of crashing

Quick Check 

m = {a:{b:{c:{d:{e:"hello"}}}}};

console.log(getMessageProperty(m,"a.b.c.d"))
console.log(getMessageProperty(m,"a.j.c.d"))

{ e: 'hello' }
undefined

instead of with current code 

        result = ( typeof obj[key] !== "undefined" ? obj[key] : undefined);
                              ^

TypeError: Cannot read property 'c' of undefined

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

update getObjectProperty(msg,expr) to support invalid expression (expr) to return undefined instead of crashing

Quick Check 

m = {a:{b:{c:{d:{e:"hello"}}}}};

console.log(getMessageProperty(m,"a.b.c.d"))
console.log(getMessageProperty(m,"a.j.c.d"))

With proposed fix 
{ e: 'hello' }
undefined

With current Code

Run lead to 

        result = ( typeof obj[key] !== "undefined" ? obj[key] : undefined);
                              ^

TypeError: Cannot read property 'c' of undefined
## Checklist

- [X ] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by knolleary** [comment]
Hi @abruno06 

this behaviour is part of the external API of Node-RED. Whether it's good or bad, it isn't something we can change just like that.

It is also behaviour we rely on in some places - which is why we have unit tests for it that this change breaks.

**Comment by abruno06** [comment]
Hello, 

I understand that it may be risky changed and after reading the UT, I have been able to found what you explain.
it may then be good to amend the function specification to make sure it clearly indicate that an error is raised that if a 'parent' element did not exist.

By chance do you know a place in the code where this is used because I would like understand what benefit it is giving of using try/catch approach versus having 'undefined' in all case.

Thanks

**Comment by knolleary** [comment]
I don't think it was entirely intentional to have that behaviour, but that is the behaviour we have.

Given the expression `a.b.c`:
 -  if `c` doesn't exist, you'll get `undefined`
 - if `b` doesn't exist you'll get the error.

I can't remember if we actually make use of that distinction anywhere. You are right, the function docs should be updated to document this behaviour.

**Comment by abruno06** [comment]
I can close this request and create one to update the comment if it make sens

**Pull request closed without merging**
