### PR TITLE
Update express.js response object method call.

### PR DESCRIPTION
**Pull request by n370**
This will make Express stop logging deprecation warns 
to the console.

### CODE REVIEW

**Comment by knolleary** [comment]
Hi, thanks for raising this.

We don't yet support Express 4.0 - we have an open issue to migrate to 4.0 here: #333. We cannot make any changes that would break 3.x users - ie, everyone who has npm installed node-red as it is today. This change would do that as `sendFile` doesn't exist in 3.x.

The right change would check for the existence of `sendFile` and only use it if its there, otherwise fall back to `sendfile`.

Also, as per our contribution guidelines, we require a signed CLA before we can accept any pull-request.

Nick

**Comment by n370** [comment]
Hi nick, thanks for getting back. 

I'd be glad to address your concerns if you tell me it is a valuable contribution anyway. In this case how should I submit my signed CLA back to you?

Consider adding these detailed instructions to the contributing guide, It might save you from having to explain it over and over again for folks like me.

**Comment by knolleary** [comment]
Hi @n370 - details in the contributing guide [here](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md#contributor-license-agreement)

**Comment by dceejay** [comment]
red/api/theme.js would also need attention

**Comment by n370** [comment]
Ohh, okay I should've read the PDF. Sorry about that @knolleary.

I'll take a look at that @dceejay.

**Comment by knolleary** [comment]
The next release of node-red moves to Express 4 - and all necessary changes have been made.

**Pull request closed without merging**
