### PR TITLE
Permit plugin theme to theme monaco editor

### PR DESCRIPTION
**Pull request by Steve-Mcl**
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes
As discussed on slack and touched on in forum, permit them plugin to select a core theme or provide custom theme

### Outline...

The modification permits the plugin theme writer to either specify a core theme or provide own custom theme.

### Examples of plugin providing monaco theme... 

* See **Revised plugin setup** in [this comment](https://github.com/node-red/node-red/pull/3084#issuecomment-890323358) below

### NOTES
* ~~Both the `monacoTheme` theme  (set in plugin) and `codeEditor.theme` theme  in `settings.js` will be loaded into monaco to  permit user switching between them (f1 -> set theme)~~
* ~~If `codeEditor.theme` is set, it will take precedence over the themes `monacoTheme` and set as the active monaco theme by default (but as mentioned, user can switch using f1)~~
* I couldnt quite grasp what you meant on the slack thread by "make `settings()` an async function" - it seems `context()` is always called before `settings()` so for now I have simply set `themeSettings.monacoTheme = themePlugin.monacoTheme;` inside the `context()` function. Seems to work but I figure you said this for some specific criteria I am not getting.

* See **Revised plugin setup** in [this comment](https://github.com/node-red/node-red/pull/3084#issuecomment-890323358) below

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by knolleary** [comment]
I think there is unnecessary duplication of logic here between `editorTheme.monacoTheme` and the property we already have `editorTheme.codeEditor.options.theme`.

I suggest if a plugin provides the `monaco-theme` property, then we should be setting `editorTheme.codeEditor.options.theme` to its value - (if not already set), rather than introducing a new property.

The code in the editor then only needs to check that one property - if a string, assume its a theme name to load, if an object, apply the theme directly.

**Comment by Steve-Mcl** [comment]
> I suggest if a plugin provides the monaco-theme property, then we should be setting editorTheme.codeEditor.options.theme to its value - (if not already set), rather than introducing a new property

I think that is doable. Will adjust PR later this evening when I get home.

**Comment by Steve-Mcl** [comment]
Hi Nick, re-used `editorTheme.codeEditor.options.theme` and reduced duplication

**Comment by Steve-Mcl** [comment]
Just a thought...

As well as permitting theme selection, should we permit the theme writer to be able to set fontSize, fontType, minimap visibility, etc also?  (these are not specified in the monaco theme, but the monaco editor options)

This could be done by permitting the plugin to provide a `monacoOptions` object for merging with `codeEditor.options`?

**Comment by Steve-Mcl** [comment]
@knolleary I tweaked the implementation to permit a theme writer to also affect other options in monaco. E.g. the theme plugin can now hide the minimap or set the font ligatures/size/weight etc.

### QUESTION
Should the plugins `monacoOptions` override `codeEditor.options` or should `codeEditor.options` (if set) always take precedence?

**_Currently (in this PR) `monacoOptions` will override `codeEditor.options`._** The logic made sense when I wrote it but suspect it should be reversed.

If this should be reversed, then we simply need to change `theme.codeEditor.options = Object.assign({}, theme.codeEditor.options, themePlugin.monacoOptions);` to `theme.codeEditor.options = Object.assign({}, themePlugin.monacoOptions, theme.codeEditor.options);` so that any props explicitly set in `theme.codeEditor.options` take precedence over the plugins settings.

## Revised plugin setup for affecting options of monaco...

### Plugin set monaco options directly and use core monaco theme by name...
```js
  RED.plugins.registerPlugin("midnight-red2", {
    type: "node-red-theme",
    css: [
      "theme.min.css",
      "theme-customizations.min.css"
    ],
    monacoOptions: {
      theme: "vs-dark",
      fontLigatures: true,
      fontSize: 14,
      fontLigatures: true,
      fontFamily: "Cascadia Code, Fira Code, Consolas, 'Courier New', monospace",
      minimap: { enabled: false }
    }
  })
```

### Plugin set monaco options directly and monaco theme via a relative theme JSON file...
```js
RED.plugins.registerPlugin("midnight-red3", {
    type: "node-red-theme",
    css: [
      "theme.min.css",
      "theme-customizations.min.css"
    ],
    monacoOptions: {
      theme: require("./midnight-red-monaco-theme.json"),
      fontLigatures: true,
      fontSize: 14,
      fontLigatures: true,
      fontFamily: "Cascadia Code, Fira Code, Consolas, 'Courier New', monospace",
      minimap: { enabled: false }
    }
  })
```

### Plugin set monaco theme directly...
```js
  RED.plugins.registerPlugin("midnight-red", {
    type: "node-red-theme",
    css: [
      "theme.min.css",
      "theme-customizations.min.css"
    ],
    monacoOptions: {
      fontLigatures: true,
      fontSize: 14,
      fontLigatures: true,
      fontFamily: "Cascadia Code, Fira Code, Consolas, 'Courier New', monospace",
      minimap: { enabled: false },
      theme: {
        "base": "vs-dark",
        "inherit": true,
        "colors": {
          "editor.foreground": "#CCC",
          "editor.background": "#434954",
          "editor.selectionBackground": "#80000080",
          "editor.lineHighlightBackground": "#80000040",
          "editorCursor.foreground": "#7070FF",
          "editorWhitespace.foreground": "#BFBFBF"
        },      
        "rules": [
            {
                "background": "434954",
            },
            {
                "foreground": "aeaeae",
                "fontStyle": "italic",
                "token": "comment"
            },
            {
                "foreground": "d8fa3c",
                "token": "string"
            },
            {
                "foreground": "d8fa3c",
                "fontStyle": "bold",
                "token": "constant"
            },
        ]
      }
    }
  })
```

**Comment by dceejay** [comment]
I suspect it should be the other way round as at the end of the day the user may want to override the theme so the codeEditor options should take priority

**Comment by bonanitech** [comment]
I agree with @dceejay. I also think that `codeEditor.options` should take priority in this case.

**Comment by Steve-Mcl** [comment]
@dceejay @bonanitech 

I think we are all on the same page. I've updated the PR to swap priorities

**Comment by Steve-Mcl** [comment]
Hi @knolleary, @dceejay 

Sorry for the direct tag (never sure if you get notified when a comment is added to a PR). 

@bonanitech is keen to know if this will make the 2.1 cut so he can update themes.

Also, do I need to merge latest `dev` into this and push update?

Cheers.

**Comment by knolleary** [comment]
Thanks for the nudge @Steve-Mcl 

I'll have a docs PR for you to review at some point  as I want to write a 'How to create a Theme Plugin' docs for https://nodered.org/docs/api/ui

**Comment by bonanitech** [comment]
@knolleary @Steve-Mcl you guys rock! Thank you.

**Comment by knolleary** [comment]
@Steve-Mcl @bonanitech please have a look at the new Theme Plugin docs page and let me know what you think.

https://nodered.org/docs/api/ui/themes/

**Comment by bonanitech** [comment]
It looks awesome!

I would only suggest you add a little padding after the content.

**Comment by Steve-Mcl** [comment]
Hi Nick, I havent carried out the instructions as a step by step but as far as I can see, it looks ok.

(very minor) suggestions on the Monaco parts....
* Minor nit-pick
  * change "provide custom Monaco editor options, include what theme it should use." to "provide custom Monaco editor options including what theme it should use."
* Add note and link to Additional Monaco options (`istandaloneeditorconstructionoptions` settings)  
* 1st code example: change 1st line to `RED.plugins.registerPlugin("midnight-red", {`
  * use `midnight-red` instead of `midnight-red2` which was from a test I had done
* 1st code example: remove duplicate `fontLigatures: true,` entry from `monacoOptions`
* 2nd code example: include the `monacoOptions: {` part to give user some context
* Below 2nd code example: Indicate that the theme can be stored in a separate file & `require`d 
  *   Maybe add a code example `monacoOptions: {  theme: require("midnight-red-monaco.json") },`?

<br>

<br>

## Theming the Monaco editor
As well as providing custom CSS and scripts, a theme plugin can also provide custom Monaco editor options including what theme it should use.

### Setting the Monaco theme by name
Monaco comes with a number of built-in themes available. The full list is [here](https://github.com/node-red/node-red/tree/master/packages/node_modules/%40node-red/editor-client/src/vendor/monaco/dist/theme). Additional settings for Monaco options can be found [here](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandaloneeditorconstructionoptions.html)

The name of the theme can be provided in the plugin settings:
```
RED.plugins.registerPlugin("midnight-red2", {
   type: "node-red-theme",
   css: "style.css",
   monacoOptions: {
     theme: "vs-dark", // Monaco theme name
     fontSize: 14,
     fontLigatures: true,
     fontFamily: "Cascadia Code, Fira Code, Consolas, 'Courier New', monospace",
     minimap: { enabled: false }
   }
 })
```


### Setting a custom Monaco theme
Rather than identify a theme by name. the monacoOptions.theme setting can be used to provide a custom Monaco theme object:
```
   monacoOptions: {
      theme: {
        "base": "vs-dark",
        "inherit": true,
        "colors": {
          "editor.foreground": "#CCC",
          "editor.background": "#434954",
          "editor.selectionBackground": "#80000080",
          "editor.lineHighlightBackground": "#80000040",
          "editorCursor.foreground": "#7070FF",
          "editorWhitespace.foreground": "#BFBFBF"
        },      
        "rules": [
            {
                "background": "434954",
            },
            {
                "foreground": "aeaeae",
                "fontStyle": "italic",
                "token": "comment"
            },
            {
                "foreground": "d8fa3c",
                "token": "string"
            },
            {
                "foreground": "d8fa3c",
                "fontStyle": "bold",
                "token": "constant"
            },
        ]
      }
    }
```

NOTES...
* The Monaco theme JSON can also be saved to a separate JSON file and `require`d by the plugin
* The specific details of how to create a Monaco theme is beyond the scope of our documentation.

**Pull request merged**
