### PR TITLE
Update monaco to latest and node types to 18 LTS

### PR DESCRIPTION
**Pull request by Steve-Mcl**
## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes

Updates Monaco to 0.47
Update node js typings to 18 LTS

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ ] I have run `npm run test` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by hardillb** [comment]
FYI default nodejs for NR 4.0 docker will be v20

**Comment by Steve-Mcl** [comment]
> FYI default nodejs for NR 4.0 docker will be v20

Oh, I missed that!  could of sworn I seen V18 mentioned in the release 🤔

**Comment by Steve-Mcl** [comment]
From [the release](https://discourse.nodered.org/t/node-red-4-0-0-beta-1-released/86433)

> Node-RED 4.x requires at least Node 18.x. We recommend using Node 20

Are we going to lock the engine ver at 20 for final release @hardillb ?

**Comment by hardillb** [comment]
Min support is 18 add there will be docker containers, the default latest tag will be 20

**Review by knolleary — APPROVED** [review]

**Pull request merged**
