### PR TITLE
Add support for accessing node id & name as environment variable

### PR DESCRIPTION
**Pull request by HiroyasuNishiyama**
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes

This PR adds support for accessing node id and node name using environment variable as discussed in:
https://discourse.nodered.org/t/proposal-make-node-name-accessible-as-environment-variable/56587/5

- id: `NODE_ID`
- name: `NODE_NAME`

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [x] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by knolleary** [comment]
Should we also add equivalent env vars at the flow level?

 - `FLOW_NAME`
 - `FLOW_ID`

**Comment by HiroyasuNishiyama** [comment]
Thank you.
I have added `FLOW_NAME` and `FLOW_ID` as new environment variables according to your suggestion.
Similarly added `GROUP_NAME` and `GROUP_ID` for accessing group information.

**Comment by knolleary** [comment]
I have a last minute concern that introducing these env vars will break existing flows that might already be using these env var names.

Should we consider adding `NR_` as a prefix to them to reduce the changes of a collision? That would also help in the future if we add `NODE_PATH` as `NR_NODE_PATH` would not clash with any existing env var

**Comment by HiroyasuNishiyama** [comment]
For the same reason that the original proposal suggested `_` as a prefix, I modified it to prefix the name with` NR_` according to your suggestion.

**Comment by knolleary** [comment]
Thank you @HiroyasuNishiyama

**Pull request merged**
