### PR TITLE
Fix UI testing on the latest Google Chrome

### PR DESCRIPTION
**Pull request by kazuhitoyokoi**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes
Currently, UI testing doesn't work because the handling of the latest Google Chrome seems to have been changed. To work correctly, I updated the modules and modified the settings of the Webdriver IO.

## Checklist
- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by knolleary** [comment]
Thanks!

**Comment by knolleary** [comment]
Subtle issue in this PR - the `scripts/install-ui-test-dependencies.sh` file has lost its executable permission. Not a big problem and something I can tidy up, but just one to watch out for.

**Comment by kazuhitoyokoi** [comment]
Thank you for the information. On bash on Windows, permissions of all files are 666 but developers seem to be able to change it using git command. I will use this git command option next time. 👍

**Comment by kazuhitoyokoi** [comment]
I tried to use the command, `git update-index --add --chmod=+x scripts/install-ui-test-dependencies.sh` and submitted the pull request, #2383. I learned it.

**Pull request merged**
