### PR TITLE
Translations and little view updates

### PR DESCRIPTION
**Pull request by Kroderia**
Fix and Add Chinese translations to match all en-US's items  
Little updates to create better view for some core nodes

### CODE REVIEW

**Comment by knolleary** [comment]
Hi,

thanks for the translations.

As for changes to the node UIs, it would be very helpful if you summarised the changes you are making. Right now I am having to do before/after comparisons of each node you have touch to understand what you've done.

Nick

**Comment by knolleary** [comment]
Some problems with your proposals:

presentation1

Top row - Status node
Bottom row - Debug node

Left-hand image - 0.18
Right-hand image - this PR

Status node - the label is now split over two lines.
Debug node - the checkboxes don't line up at all and the whole dialog is being forced to be extra wide.

**Comment by Kroderia** [comment]
Thanks for your time and sorry for missing testing.  
It works fine in Chinese environment. I will fix these later and recreate a PR.

**Comment by dceejay** [comment]
maybe split into two - one for the translations and one for ui ?

**Comment by Kroderia** [comment]
As you wish.

**Comment by dceejay** [comment]
maybe make status label have a min-width so it will line up when using shorter Chinese label ?

**Pull request closed without merging**
