### PR TITLE
updated/added DE translations of security term

### PR DESCRIPTION
**Pull request by heikokue**
- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes
updated/added german transalations of security term in editor-client/locales/de/editor.json

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by dceejay** [comment]
Thanks for raising all these PR - I can see the discussion is getting lively and hopefully productive. 
Are you able to sign/click the CLA such that we are able to merge them as and when they come to a consensus ?

**Comment by heikokue** [comment]
> Are you able to sign/click the CLA such that we are able to merge them as and when they come to a consensus ?
I already did it some days ago.

**Comment by dceejay** [comment]
Maybe you used a different user id ?

**Comment by heikokue** [comment]
> Maybe you used a different user id ?

grafik

**Comment by heikokue** [comment]
the user id is correct, but the email is different.
I added my other address to github settings and hope that works......

**Comment by heikokue** [comment]
merged into #2806

**Pull request closed without merging**
