### PR TITLE
Multiple catch nodes in same tab behavior option.

### PR DESCRIPTION
**Pull request by mauriciom75**
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes

Hello, there is a new proposal related with pull request #1538 :

Modify the catch node to accept a new option:
"all nodes"
"selected nodes"
**"unselected nodes"**

It will be executed if no cath node with specific target was previously executed for an error.

It is useful when in a tab we have 1 catch node catching errors of particular nodes and also we have 1 catch node or more catching errors of the rest of the nodes ("catch all"). And also we do not want that the errors of particular nodes are caught 2 times.

This change facilitates maintenance, because if we do not want the error to be trapped 2 times, we have to configure each catch node with a disjoint list of nodes.
In this way we only have to configure the catch nodes with the nodes that interest us, and have a catch node configured with "catch all" for the rest of nodes.

this change does not affect the current imaplementations, and by default the configuration maintains the current behavior. Except in the order of execution of catch nodes in the same tab that I previously thought was in order of creation of the nodes.

If you think the change can move forward, I can add tests and locales.

Internally; I added the catchPedence field to be able to execute the specific catch nodes first, then the "unselected" ones and then the "catch all" ones. If a catch node of type "selected" was executed previously, then will not execute the catch node of type "unselected".

Example:
[{"id":"95313975.c141f8","type":"inject","z":"a542603f.c5869","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":120,"y":200,"wires":[["89be33f5.500de","bc2f994c.6a7178"]]},{"id":"3001c4ab.4bb6cc","type":"debug","z":"a542603f.c5869","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"error","x":680,"y":300,"wires":[]},{"id":"89be33f5.500de","type":"function","z":"a542603f.c5869","name":"error1","func":"node.error(\"Error1\",msg)\n\nreturn msg;","outputs":1,"noerr":0,"x":290,"y":120,"wires":[[]]},{"id":"dc952d33.e2208","type":"debug","z":"a542603f.c5869","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"error","x":680,"y":120,"wires":[]},{"id":"51cd30bc.e869a","type":"catch","z":"a542603f.c5869","name":"","scope":null,"unselectedNodes":true,"x":480,"y":260,"wires":[["3001c4ab.4bb6cc"]]},{"id":"ecd2eaba.c86f28","type":"catch","z":"a542603f.c5869","name":"","scope":["89be33f5.500de"],"unselectedNodes":true,"x":490,"y":100,"wires":[["dc952d33.e2208"]]},{"id":"bc2f994c.6a7178","type":"function","z":"a542603f.c5869","name":"error2","func":"node.error(\"Error2\",msg)\n\nreturn msg;","outputs":1,"noerr":0,"x":290,"y":220,"wires":[[]]}]

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

We were discussing a bit in the previous pull request #1538

### CODE REVIEW

**Comment by mauriciom75** [comment]
Cancelled by travis errors.

**Comment by mauriciom75** [comment]
Cancelled by travis errors. Delete package-lock.json

**Comment by knolleary** [comment]
Hi @mauriciom75 

thanks for this. Given some of the internal refactoring done in the `dev` branch, I've implemented this feature in a slightly different way. The basic concept is the same - and thank you for raising it.

We'll be releasing 0.20.0-beta.5 this week so you can try it out then.

**Comment by mauriciom75** [comment]
Ok, thank you! I Will try it!

**Comment by mauriciom75** [comment]
Hello, I tried an example flow and some variants with the version 0.20.0-beta.5. I used the option "Ignore errors handled by other Catch nodes" and it worked very well for me.
Thank you!

**Pull request closed without merging**
