### PR TITLE
Implementing CI/CD pipeline with Jenkins pipeline and Dockerized the application

### PR DESCRIPTION
**Pull request by Anurag000-rgb**
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by hardillb** [comment]
Please fill out the full template you were shown when opening this PR.

We need a very clear description of what the changes are and a link to the Node-RED forum or Slack where this change was discussed ahead of time.

**Comment by Anurag000-rgb** [comment]
I have Dockerized the Application with implementing a CI/CD pipeline with jenkins

**Comment by hardillb** [comment]
And why would we want that?

What benefits does it offer over what we already have?

The project already makes Docker containers available under the https://github.com/node-red/node-red-docker project

And already runs a set of tests using the GitHub Action when ever PRs are merged.

Looking at the files changed I can't see what if any tests are run by Jenkins

As I asked earlier we need a clear description of why this is good for the project, and where it has already been discussed before the Pull Request was raised as mentioned in the [CONTRIBUTING.md](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)

**Comment by dceejay** [comment]
It looks like the Jenkins file is set specifying your account. Not sure we would want to set that as a default. The grunt container you pull in is also over a year old, not sure if that’s the official one.

**Comment by knolleary** [comment]
Hi @Anurag000-rgb 

Thank you for the contribution. However, as the others have pointed out, this isn't something we'd want to merge into this repository. We already have a dockerized version of the app in the https://github.com/node-red/node-red-docker repository. Nor do we have any use of a Jenkins pipeline.

If there are some specific things you are looking for, please do raise them on the [forum](discourse.nodered.org) first so we can discuss whether they make sense.

**Pull request closed without merging**
