### PR TITLE
Fixed the problem where RED._ was unavailable in the module code

### PR DESCRIPTION
**Pull request by kallenboone**
For each affected module I moved the code run at module load time into a function that is then called in the module's init function to ensure that RED._ is already initialized when needed.

### CODE REVIEW

**Comment by knolleary** [comment]
Hi @kallenboone - sorry to nitpick, but can you swap your whitespace tabs for 4-spaces?

Thanks.

**Comment by kallenboone** [comment]
No prob, @knolleary. I just committed the tab to space conversion, and I've updated my editor preferences to use spaces going forward.

**Comment by knolleary** [comment]
Hi, can you squash your commits down to just one please? Don't want multiple needless 'merge' commits  in the log. Thanks.

**Comment by kallenboone** [comment]
I squashed my two commits with a rebase command, and I rolled back the merge commits using reset. I'm a bit of a newbie to Git still, though, and I'm not sure if that approach was the best way (I did a lot of trial and error first occasionally fearing that I had screwed up my repo). How should I keep my fork up to date while avoiding the merge commits in the future?

**Comment by kallenboone** [comment]
Also, I just pushed a fix to a bug I found in editor.js. I squashed that change into the previous commit, but I though I should mention that there was an additional change added.

**Pull request merged**
