### PR TITLE
CSV node check header properties for ' and "

### LINKED ISSUE #3919: CSV node does not cope with single quote characters in property names
### Current Behavior

If an array of objects is passed to the CSV node and it is configured to generate headers then, if any of the properties includes a single quote character, then it fails with errors like
Error: Invalid property expression: unexpected array expression at position 12

Confirmed by @TotallyInformation in https://discourse.nodered.org/t/csv-node-does-not-cope-with-quotes-in-property-names-bug-or-feature/69027

### Expected Behavior

It should not fail

### Steps To Reproduce

Run the example flow below

### Example flow

```
[{"id":"0a117283c6ec0e9a","type":"inject","z":"c57d82f577bb37d5","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[{\"a'a\":\"A1\",\"b\":\"B1\"},{\"a'a\":\"A2\",\"b\":\"B2\"}]","payloadType":"json","x":160,"y":460,"wires":[["e9b9c226cb22fc89"]]},{"id":"e9b9c226cb22fc89","type":"csv","z":"c57d82f577bb37d5","name":"","sep":",","hdrin":"","hdrout":"all","multi":"one","ret":"\\n","temp":"","skip":"0","strings":true,"include_empty_strings":"","include_null_values":"","x":330,"y":460,"wires":[["8a79b816b21ebf6f"]]},{"id":"8a79b816b21ebf6f","type":"debug","z":"c57d82f577bb37d5","name":"debug 28","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":500,"y":460,"wires":[]}]```
```

### Environment

- Node-RED version: 3.2.0
- Node.js version: 16.17.1
- npm version: 8.15.0
- Platform/OS: Ubuntu
- Browser: Chrome

### PR DESCRIPTION
**Pull request by dceejay**
and add test
to close #3919

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

Fixes Issue #3919 - if property names contain quotes (unusual but no impossible) then we should output then as the header line of the CSV correctly rather than breaking

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [x] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by knolleary** [comment]
Merging is blocked until #3922 is merged and this branch rebased to pickup that fix.

**Comment by Steve-Mcl** [comment]
@dceejay 

Dave, there are more issues I'm afraid. Look at the examples below.





image


```
[{"id":"0a117283c6ec0e9a","type":"inject","z":"10ece3ab98e93683","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[{\"c\\\"c\":3,\"d.d\":4,\"b,b\":2,\"e`e\":5,\"a'a\":1},{\"d.d\":2,\"e`e\":1,\"b,b\":4,\"c\\\"c\":3,\"a'a\":5}]","payloadType":"json","x":1450,"y":160,"wires":[["e9b9c226cb22fc89"]]},{"id":"e9b9c226cb22fc89","type":"csv","z":"10ece3ab98e93683","name":"","sep":",","hdrin":"","hdrout":"all","multi":"one","ret":"\\n","temp":"","skip":"0","strings":true,"include_empty_strings":"","include_null_values":"","x":1630,"y":160,"wires":[["8a79b816b21ebf6f"]]},{"id":"8a79b816b21ebf6f","type":"debug","z":"10ece3ab98e93683","name":"debug 28","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1820,"y":160,"wires":[]},{"id":"87702dd4078dd355","type":"comment","z":"10ece3ab98e93683","name":"No col/template object data only.  Outputs invalid header   c\"c,d.d,\"b,b\",e`e,a'a   (RFC4180 2.6/2.7)","info":"#### Demo 1 - no column template\n\nInput data\n```\n[\n    {\"c\\\"c\":3,\"d.d\":4,\"b,b\":2,\"e`e\":5,\"a'a\":1},\n    {\"d.d\":2,\"e`e\":1,\"b,b\":4,\"c\\\"c\":3,\"a'a\":5}\n]\n```\n\nExtracts col template...\n```\n['c\"c', 'd.d', 'b,b', 'e`e', \"a'a\"]\n//c\"c,d.d,b,b,e`e,a'a               as a CSV string\n```\n\nAccording to RFC4180 2.6 & 2.7 the CSV generated for the template is invalid:\n\n> 2.6\n> Fields containing line breaks (CRLF), double quotes, and commas\n> should be enclosed in double-quotes\n\n> 2.7\n> If double-quotes are used to enclose fields, then a double-quote\n> appearing inside a field must be escaped by preceding it with\n> another double quote\n\ni.e. the column template should be...\n\n```\n\"c\"\"c\",d.d,\"b,b\",e`e,a'a\n```","x":1730,"y":120,"wires":[]},{"id":"15e327549fb3d8a8","type":"inject","z":"10ece3ab98e93683","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[{\"c\\\"c\":3,\"d.d\":4,\"b,b\":2,\"e`e\":5,\"a'a\":1},{\"d.d\":2,\"e`e\":1,\"b,b\":4,\"c\\\"c\":3,\"a'a\":5}]","payloadType":"json","x":1450,"y":300,"wires":[["8b44ac2b17a19652"]]},{"id":"8b44ac2b17a19652","type":"csv","z":"10ece3ab98e93683","name":"","sep":",","hdrin":"","hdrout":"all","multi":"one","ret":"\\n","temp":"a'a,\"b,b\",c\"c,d.d,e`e","skip":"0","strings":true,"include_empty_strings":"","include_null_values":"","x":1630,"y":300,"wires":[["6af93e801ca72838"]]},{"id":"6af93e801ca72838","type":"debug","z":"10ece3ab98e93683","name":"debug 109","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1830,"y":300,"wires":[]},{"id":"4715772ba53f646c","type":"comment","z":"10ece3ab98e93683","name":"Incorrectly parses `col`  a'a,\"b,b\",c\"c,d.d,e`e  - as -  ['a'a,b', 'b,cc', 'd.d', 'e`e']      (RFC4180 2.6)","info":"#### Demo 2\n\nColumn Template\n```\na'a,\"b,b\",c\"c,d.d,e`e\n```\n\nparses as\n```\n['a'a,b', 'b,cc', 'd.d', 'e`e']\n```\n\nAccording to RFC4180 2.6 the CSV for the template is invalid:\n> Fields containing line breaks (CRLF), double quotes, and commas\n>  should be enclosed in double-quotes\n\n\nUsing https://www.npmjs.com/package/@vanillaes/csv\n\n```\ncsv.parse('a\\'a,\"b,b\",c\"c,d.d,e`e')\n//Uncaught Error: CSVError: Illegal state [row:1, col:3]\n```","x":1710,"y":260,"wires":[]},{"id":"f5feaf8eada6049b","type":"inject","z":"10ece3ab98e93683","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[{\"c\\\"c\":3,\"d.d\":4,\"b,b\":2,\"e`e\":5,\"a'a\":1},{\"d.d\":2,\"e`e\":1,\"b,b\":4,\"c\\\"c\":3,\"a'a\":5}]","payloadType":"json","x":1450,"y":700,"wires":[["7b8d6e39682d2307"]]},{"id":"7b8d6e39682d2307","type":"csv","z":"10ece3ab98e93683","name":"","sep":",","hdrin":"","hdrout":"all","multi":"one","ret":"\\n","temp":"a'a,\"b,b\",\"c\"\"c\",d.d,e`e","skip":"0","strings":true,"include_empty_strings":"","include_null_values":"","x":1630,"y":700,"wires":[["09fed6ead887b782"]]},{"id":"09fed6ead887b782","type":"debug","z":"10ece3ab98e93683","name":"debug 110","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1830,"y":700,"wires":[]},{"id":"e367eaebdec89b4a","type":"comment","z":"10ece3ab98e93683","name":"Valid CSV `col` incorrectly parsed   a'a,\"b,b\",\"c\"\"c\",d.d,e`e  →  a'a,\"b,b\",cc,d.d,e`e","info":"#### Demo 5\n\nColumn Template\n```\na'a,\"b,b\",\"c\"\"c\",d.d,e`e\n```\n\nparses as\n```\n['a'a', 'b,b', 'cc', 'd.d', 'e`e']\n//a\\'a,\"b,b\",cc,d.d,e`e            as a CSV string\n```\n\nAccording to RFC4180 2.7 this should be\n```\n[ \"a'a\", 'b,b', 'c\"c', 'd.d', 'e`e' ]\n// a'a,\"b,b\",\"c\"\"c\",d.d,e`e           as a CSV string\n```\n\n\nUsing https://www.npmjs.com/package/@vanillaes/csv\n\n```\ncsv.parse('a\\'a,\"b,b\",\"c\"\"c\",d.d,e`e')\n// [ \"a'a\", 'b,b', 'c\"c', 'd.d', 'e`e' ]\n```\n\n","x":1670,"y":660,"wires":[]},{"id":"4fe89a759501f96f","type":"csv","z":"10ece3ab98e93683","name":"","sep":",","hdrin":"","hdrout":"all","multi":"one","ret":"\\n","temp":"a'a,\"b,b\",c\"\"c,d.d,e`e","skip":"0","strings":true,"include_empty_strings":"","include_null_values":"","x":1630,"y":440,"wires":[["01560e6b446b8b27"]]},{"id":"286f0e9e06ada8b0","type":"inject","z":"10ece3ab98e93683","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[{\"c\\\"c\":3,\"d.d\":4,\"b,b\":2,\"e`e\":5,\"a'a\":1},{\"d.d\":2,\"e`e\":1,\"b,b\":4,\"c\\\"c\":3,\"a'a\":5}]","payloadType":"json","x":1450,"y":440,"wires":[["4fe89a759501f96f"]]},{"id":"01560e6b446b8b27","type":"debug","z":"10ece3ab98e93683","name":"debug 108","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1830,"y":440,"wires":[]},{"id":"b971c7dde1d9d5b6","type":"comment","z":"10ece3ab98e93683","name":"Incorrectly parses `col`  a'a,\"b,b\",c\"\"c,d.d,e`e  - as -  ['a'a,b', 'b,cc', 'd.d', 'e`e']      (RFC4180 2.6)","info":"#### Demo 3\n\nColumn Template\n```\na'a,\"b,b\",c\"\"c,d.d,e`e\n```\n\nparses as\n```\n['a'a,b', 'b,cc', 'd.d', 'e`e']\n```\n\nAccording to RFC4180 2.6 the CSV for the template is invalid:\n> Fields containing line breaks (CRLF), double quotes, and commas\n>  should be enclosed in double-quotes\n\n\nUsing https://www.npmjs.com/package/@vanillaes/csv\n\n```\ncsv.parse('a\\'a,\"b,b\",c\"\"c,d.d,e`e')\n// Uncaught Error: CSVError: Illegal state [row:1, col:3]\n```","x":1710,"y":400,"wires":[]},{"id":"7f8ae7950520433e","type":"inject","z":"10ece3ab98e93683","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[{\"c\\\"c\":3,\"d.d\":4,\"b,b\":2,\"e`e\":5,\"a'a\":1},{\"d.d\":2,\"e`e\":1,\"b,b\":4,\"c\\\"c\":3,\"a'a\":5}]","payloadType":"json","x":1450,"y":840,"wires":[["96ca0b519e4fb5cf"]]},{"id":"96ca0b519e4fb5cf","type":"csv","z":"10ece3ab98e93683","name":"","sep":",","hdrin":"","hdrout":"all","multi":"one","ret":"\\n","temp":"a'a ,\" b,b\",\" c\"\"c\",d.d, e`e","skip":"0","strings":true,"include_empty_strings":"","include_null_values":"","x":1630,"y":840,"wires":[["0432d128217f3f08"]]},{"id":"0432d128217f3f08","type":"debug","z":"10ece3ab98e93683","name":"debug 111","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1830,"y":840,"wires":[]},{"id":"2bf17037679c85db","type":"comment","z":"10ece3ab98e93683","name":"Valid CSV `col` incorrectly parsed     a'a ,\" b,b\",\" c\"\"c\",d.d, e`e  →   ['a'a', 'b,b', 'cc', 'd.d', 'e`e']  (RFC4180 2.4)","info":"#### Demo 6\n\nColumn Template\n```\na'a ,\" b,b\",\" c\"\"c\",d.d, e`e\n```\n\nparses as\n```\n['a'a', 'b,b', 'cc', 'd.d', 'e`e']\n//a'a,\"b,b\",cc,d.d,e`e             as a CSV string\n```\n\nAccording to RFC4180 2.4\n> Spaces are considered part of a field and should not be ignored\n\nSo this template should parse as\n```\n[ \"a'a \", ' b,b', ' c\"c', 'd.d', ' e`e' ]\n// a'a ,\" b,b\",\" c\"\"c\",d.d, e`e          as a CSV string\n```\n\n\nUsing https://www.npmjs.com/package/@vanillaes/csv\n\n```\ncsv.parse('a\\'a ,\" b,b\",\" c\"\"c\",d.d, e`e')\n[ \"a'a \", ' b,b', ' c\"c', 'd.d', ' e`e' ]\n\ncsv.stringify([[ \"a'a \", ' b,b', ' c\"c', 'd.d', ' e`e' ]])\n// a'a ,\" b,b\",\" c\"\"c\",d.d, e`e\n```","x":1750,"y":800,"wires":[]},{"id":"6906c507f6037bf7","type":"csv","z":"10ece3ab98e93683","name":"","sep":",","hdrin":"","hdrout":"all","multi":"one","ret":"\\n","temp":"a'a,\"b,b\",c\"\"c,d.d,e`e","skip":"0","strings":true,"include_empty_strings":"","include_null_values":"","x":1630,"y":560,"wires":[["e1cc491e0758212f"]]},{"id":"997198c671e92660","type":"inject","z":"10ece3ab98e93683","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[{\"c\\\"c\":3,\"d.d\":4,\"b,b\":2,\"e`e\":5,\"a'a\":1},{\"d.d\":2,\"e`e\":1,\"b,b\":4,\"c\\\"c\":3,\"a'a\":5}]","payloadType":"json","x":1450,"y":560,"wires":[["6906c507f6037bf7"]]},{"id":"e1cc491e0758212f","type":"debug","z":"10ece3ab98e93683","name":"debug 112","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1830,"y":560,"wires":[]},{"id":"721d9bf721697398","type":"comment","z":"10ece3ab98e93683","name":"Incorrectly parses `col`  a'a,\"b,b\",\"c\"c\",d.d,e`e  - as -  a'a,\"b,b\",cc,d.d,e`e      (RFC4180 2.7)","info":"#### Demo 4\n\nColumn Template\n```\na'a,\"b,b\",\"c\"c\",d.d,e`e\n```\n\nincorrectly parses as\n```\na'a,\"b,b\",cc,d.d,e`e\n```\n\nAccording to RFC4180 2.6 the CSV for the template is invalid:\n> Fields containing line breaks (CRLF), double quotes, and commas\n>  should be enclosed in double-quotes\n\nUsing https://www.npmjs.com/package/@vanillaes/csv\n\n```\ncsv.parse('a\\'a,\"b,b\",\"c\"c\",d.d,e`e')\n// Uncaught Error: CSVError: Illegal state [row:1, col:3]\n```","x":1690,"y":520,"wires":[]}]
```


[RFC 4180 Section#2, point#4](https://www.rfc-editor.org/rfc/rfc4180#section-2)
> Spaces are considered part of a field and should not be ignored


[RFC 4180 Section#2, point#6](https://www.rfc-editor.org/rfc/rfc4180#section-2)
> Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes


[RFC 4180 Section#2, point#7](https://www.rfc-editor.org/rfc/rfc4180#section-2)
> If double-quotes are used to enclose fields, then a double-quote appearing inside a field must be escaped by preceding it with another double quote

<br>
<br>


### Thoughts (IMHO)...
* The CSV node should be RFC 4180 compliant (if not by default, then via a checkbox option)
  * For node-red reputation purposes I think this is important 
* The built in help tip a wink to the RFC specs
* Invalid column template should cause a UI error & if deployed, a runtime error

Perhaps we might consider using a proven NPM import? I tried about 6 promising ones - none handled all 6 tests 100% apart from  https://www.npmjs.com/package/@vanillaes/csv 

<br>
<br>

### Demo details...

#### Demo 1 - no column template

Input data
```
[
    {"c\"c":3,"d.d":4,"b,b":2,"e`e":5,"a'a":1},
    {"d.d":2,"e`e":1,"b,b":4,"c\"c":3,"a'a":5}
]
```

Extracts col template...
```
['c"c', 'd.d', 'b,b', 'e`e', "a'a"]
//c"c,d.d,b,b,e`e,a'a               as a CSV string
```

According to RFC4180 2.6 & 2.7 the CSV generated for the template is invalid:

> 2.6
> Fields containing line breaks (CRLF), double quotes, and commas
> should be enclosed in double-quotes

> 2.7
> If double-quotes are used to enclose fields, then a double-quote
> appearing inside a field must be escaped by preceding it with
> another double quote

i.e. the column template should be...

```
"c""c",d.d,"b,b",e`e,a'a
```


#### Demo 2

Column Template
```
a'a,"b,b",c"c,d.d,e`e
```

parses as
```
['a'a,b', 'b,cc', 'd.d', 'e`e']
```

According to RFC4180 2.6 the CSV for the template is invalid:
> Fields containing line breaks (CRLF), double quotes, and commas
>  should be enclosed in double-quotes


Using https://www.npmjs.com/package/@vanillaes/csv

```
csv.parse('a\'a,"b,b",c"c,d.d,e`e')
//Uncaught Error: CSVError: Illegal state [row:1, col:3]
```



#### Demo 3

Column Template
```
a'a,"b,b",c""c,d.d,e`e
```

parses as
```
['a'a,b', 'b,cc', 'd.d', 'e`e']
```

According to RFC4180 2.6 the CSV for the template is invalid:
> Fields containing line breaks (CRLF), double quotes, and commas
>  should be enclosed in double-quotes


Using https://www.npmjs.com/package/@vanillaes/csv

```
csv.parse('a\'a,"b,b",c""c,d.d,e`e')
// Uncaught Error: CSVError: Illegal state [row:1, col:3]
```


#### Demo 4

Column Template
```
a'a,"b,b","c"c",d.d,e`e
```

incorrectly parses as
```
a'a,"b,b",cc,d.d,e`e
```

According to RFC4180 2.6 the CSV for the template is invalid:
> Fields containing line breaks (CRLF), double quotes, and commas
>  should be enclosed in double-quotes

Using https://www.npmjs.com/package/@vanillaes/csv

```
csv.parse('a\'a,"b,b","c"c",d.d,e`e')
// Uncaught Error: CSVError: Illegal state [row:1, col:3]
```




#### Demo 5

Column Template
```
a'a,"b,b","c""c",d.d,e`e
```

parses as
```
['a'a', 'b,b', 'cc', 'd.d', 'e`e']
//a\'a,"b,b",cc,d.d,e`e            as a CSV string
```

According to RFC4180 2.7 this should be
```
[ "a'a", 'b,b', 'c"c', 'd.d', 'e`e' ]
// a'a,"b,b","c""c",d.d,e`e           as a CSV string
```


Using https://www.npmjs.com/package/@vanillaes/csv

```
csv.parse('a\'a,"b,b","c""c",d.d,e`e')
// [ "a'a", 'b,b', 'c"c', 'd.d', 'e`e' ]
```



#### Demo 6

Column Template
```
a'a ," b,b"," c""c",d.d, e`e
```

parses as
```
['a'a', 'b,b', 'cc', 'd.d', 'e`e']
//a'a,"b,b",cc,d.d,e`e             as a CSV string
```

According to RFC4180 2.4
> Spaces are considered part of a field and should not be ignored

So this template should parse as
```
[ "a'a ", ' b,b', ' c"c', 'd.d', ' e`e' ]
// a'a ," b,b"," c""c",d.d, e`e          as a CSV string
```


Using https://www.npmjs.com/package/@vanillaes/csv

```
csv.parse('a\'a ," b,b"," c""c",d.d, e`e')
[ "a'a ", ' b,b', ' c"c', 'd.d', ' e`e' ]

csv.stringify([[ "a'a ", ' b,b', ' c"c', 'd.d', ' e`e' ]])
// a'a ," b,b"," c""c",d.d, e`e
```

**Comment by dceejay** [comment]
Not totally sure about some of those assertions... - Don't forget this is a parser to / from a JS object ... and JS property names cannot start with spaces for example - so we cannot map 1:1 and be expected to do a two way conversion.

**Comment by Steve-Mcl** [comment]
> JS property names cannot start with spaces for example - so we cannot map 1:1 and be expected to do a two way conversion.

They can...
image

<br>

> Not totally sure about some of those assertions... - Don't forget this is a parser to / from a JS object

Yes, but the examples were more about demonstrating things it does wrong (or maybe nicer to say "not RFC compliant")

Lets put it this way Dave, if a user feeds RFC compliant data into the CSV node - currently, there are several ways we "get it wrong"

For example, ```"c""c",d.d,"b,b",e`e,a'a\n3,4,2,5,1\n3,2,4,1,5``` is 100% RFC4180 compliant 
PROOF (using  https://www.npmjs.com/package/@vanillaes/csv) ...
```
csv.parse('"c""c",d.d,"b,b",e`e,a\'a\n3,4,2,5,1\n3,2,4,1,5')
// Results in ...
// [
//   [ 'c"c', 'd.d', 'b,b', 'e`e', "a'a" ],
//   [ '3', '4', '2', '5', '1' ],
//   [ '3', '2', '4', '1', '5' ]
// ]
```

ALT PROOF (from [convertcsv.com/csv-to-json.htm](https://www.convertcsv.com/csv-to-json.htm))
image
Input data for above ↑
```
"c""c",d.d,"b,b",e`e,a'a
3,4,2,5,1
3,2,4,1,5
```

CSV NODE...
image

**Comment by knolleary** [comment]
This can now be rebased with master to pickup the recent fix so we can get the tests passing cleanly before merging.

**Comment by Steve-Mcl** [comment]
> This can now be rebased with master to pickup the recent fix so we can get the tests passing cleanly before merging.

Nick, I don't think we should merge this until valid CSV data is producible. Also, @dceejay is working on a separate branch : [CSV-handle-quotes-and-spaces](https://github.com/node-red/node-red/tree/CSV-handle-quotes-and-spaces)

**Comment by dceejay** [comment]
Naturally I disagree. This PR does fix the immediate issue that crashes the flow. The other branch to produce "more correct" CSV is a major breaking change that will upset flows, and will need careful introduction.

**Comment by Steve-Mcl** [comment]
> Naturally I disagree. This PR does fix the immediate issue that crashes the flow.

Sorry Dave, in that sense, I retract my previous statement. 

Let me know if you want any help or legs or testing on your other branch.

**Comment by dceejay** [comment]
@knolleary - it is already based on master  - rebasing it does re-run test - but still fails

**Pull request merged**
