### PR TITLE
Drop EOL Node 14

### PR DESCRIPTION
**Pull request by Rotzbua**
- [x] Bugfix
- [x] Breaking
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

Node 14 was removed from test matrix. #4084
Since it is not tested anymore it should not be allowed to run on these version.

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
Some other places to update:

* https://github.com/node-red/node-red/blob/master/packages/node_modules/node-red/red.js#L349-L350
* https://github.com/node-red/node-red/blob/master/packages/node_modules/node-red/lib/red.js#L30

**Comment by Rotzbua** [comment]
@Steve-Mcl Thanks for review 👍 
Do not forget that the development branch is the `dev` and not `master`.

**Comment by Steve-Mcl** [comment]
> Do not forget that the development branch is the `dev` and not `master`

I noticed after posting but I was certain you'd know what I meant 🤔😂

**Review by knolleary — APPROVED** [review]

**Comment by knolleary** [comment]
We are reviewing our plans around the release schedule. The focus right now is to get 3.1 released - we aren't making any additional changes to the node.js support in that release beyond what we already have. Once we get that done, we'll shift focus to 4.x and make the necessary updates to the code and test matrix.

**Comment by ZJvandeWeg** [comment]
@Rotzbua If/when this gets merged, can you take a look at updating: https://nodered.org/docs/faq/node-versions too?

**Comment by knolleary** [comment]
Superseded by https://github.com/node-red/node-red/pull/4571

**Pull request closed without merging**
