### PR TITLE
add express-session memorystore without leaks

### PR DESCRIPTION
**Pull request by roccomuso**
## Types of changes

What types of changes does your code introduce?

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

Addressing `express-session` memory leak #1434 

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by antoniomuso** [comment]
Is this gonna be merged soon?

**Comment by knolleary** [comment]
@antoniomuso it will be merged ahead of the next major release of Node-RED. Given the nature of the change, I need to set aside some time to properly test it. So it's sat in a queue of work I have to do.

**Comment by knolleary** [comment]
Thanks!

**Comment by roccomuso** [comment]
@knolleary keep up the good work!

**Pull request merged**
