### PR TITLE
Add support of new SUBFLOW UI

### PR DESCRIPTION
**Pull request by HiroyasuNishiyama**
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes

This PR add support for new UI definition feature for SUBFLOW described at https://github.com/node-red/designs/tree/master/designs/subflow-property-ui.

With this PR Node-RED users can define SUBFLOW settings panel UI within editor.

- Example of UI definition:

スクリーンショット 2019-06-07 17 49 27

- Example of defined UI

スクリーンショット 2019-06-07 17 48 46

- Sample flow:

```
[{"id":"2e434a18.e7c0a6","type":"tab","label":"String Util","disabled":false,"info":""},{"id":"abe77105.3c0e9","type":"tab","label":"String Replace","disabled":false,"info":""},{"id":"7d7d4d9.e1d00b4","type":"tab","label":"Basic Tests","disabled":false,"info":""},{"id":"9cd15433.4d8a48","type":"subflow","name":"Subflow 1","info":"","category":"","in":[{"x":40,"y":80,"wires":[{"id":"af5384b7.151ab8"}]}],"out":[{"x":360,"y":80,"wires":[{"id":"af5384b7.151ab8","port":0}]}],"env":[],"ui":{"params":[]},"ui_in":{}},{"id":"4d6926d3.28e678","type":"subflow","name":"string conv","info":"# Convert String\n\nConversion type can be selected from following menu:\n\n- To Upper\n- To Lower\n- No Conv\n","category":"","in":[{"x":60,"y":160,"wires":[{"id":"f8be69e5.5f64e8"}]}],"out":[{"x":580,"y":160,"wires":[{"id":"47f27b59.4f1ff4","port":0},{"id":"86de1873.9dccd8","port":0},{"id":"f8be69e5.5f64e8","port":2}]}],"env":[],"ui":{"params":[{"id":1,"name":"","label":"<i class=\"fa fa-cog fa-spin\"/> Convert String","labels":{"ja":"<i class=\"fa fa-cog fa-spin\"/> Convert String"},"type":"label","value":""},{"id":2,"name":"MODE","label":"mode:","labels":{"ja":"mode:"},"type":"menu","value":"","items":[{"value":"To Upper","values":{"ja":"To Upper"}},{"value":"To Lower","values":{"ja":"To Lower"}},{"value":"No Conv","values":{"ja":"No Conv"}}]}]},"ui_in":{},"icon":"font-awesome/fa-edit"},{"id":"9dd21fb1.c72ce","type":"subflow","name":"replace","info":"# Replace String\n\nReplace sub-string specified by regexp by replacement.\n","category":"","in":[{"x":80,"y":80,"wires":[{"id":"fe283731.cfb608"}]}],"out":[{"x":320,"y":80,"wires":[{"id":"fe283731.cfb608","port":0}]}],"env":[],"ui":{"params":[{"id":1,"name":"","label":"<i class=\"fa fa-cog fa-spin\"/> Replace String","labels":{"ja":"<i class=\"fa fa-cog fa-spin\"/> Replace String"},"type":"label","value":""},{"id":2,"name":"OLD_STR","label":"Pattern","labels":{"ja":"Pattern"},"type":"str","value":""},{"id":3,"name":"NEW_STR","label":"Replacement","labels":{"ja":"Replacement"},"type":"str","value":""},{"id":4,"name":"IGNORE_CASE","label":"ignore case","labels":{"ja":"ignore case"},"type":"checkbox","value":"true"}]},"ui_in":{},"icon":"font-awesome/fa-neuter"},{"id":"779169c6.1fa2f8","type":"inject","z":"7d7d4d9.e1d00b4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":80,"wires":[["1ab7ca6d.6f39f6"]]},{"id":"83a0a06f.769af","type":"debug","z":"7d7d4d9.e1d00b4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":530,"y":80,"wires":[]},{"id":"af5384b7.151ab8","type":"change","z":"9cd15433.4d8a48","name":"","rules":[{"t":"set","p":"V","pt":"msg","to":"V","tot":"env"},{"t":"set","p":"V_info","pt":"msg","to":"V_info","tot":"env"},{"t":"set","p":"V_type","pt":"msg","to":"V_type","tot":"env"}],"action":"","property":"","from":"","to":"","reg":false,"x":200,"y":80,"wires":[[]]},{"id":"1ab7ca6d.6f39f6","type":"subflow:9cd15433.4d8a48","z":"7d7d4d9.e1d00b4","name":"Set Env Var","env":[{"name":"V","type":"str","value":"123"}],"x":390,"y":80,"wires":[["83a0a06f.769af"]]},{"id":"38a7a91b.4ed2b6","type":"inject","z":"7d7d4d9.e1d00b4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":200,"wires":[["67b2aa7c.ddafb4"]]},{"id":"61379e86.eea24","type":"debug","z":"7d7d4d9.e1d00b4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":530,"y":200,"wires":[]},{"id":"67b2aa7c.ddafb4","type":"subflow:9cd15433.4d8a48","z":"7d7d4d9.e1d00b4","name":"String (i18n)","env":[],"ui":{"params":[{"id":1,"name":"V","label":"Input V:","labels":{"en-US":"Input V:","ja":"Vを入力:"},"type":"str","value":""}]},"ui_in":{"1":{"name":"V","type":"str","value":"XYZ"}},"x":390,"y":200,"wires":[["61379e86.eea24"]]},{"id":"bd099777.5c3808","type":"inject","z":"7d7d4d9.e1d00b4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":260,"wires":[["498f3940.d060b8"]]},{"id":"548a2d1d.0e7094","type":"debug","z":"7d7d4d9.e1d00b4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":530,"y":260,"wires":[]},{"id":"498f3940.d060b8","type":"subflow:9cd15433.4d8a48","z":"7d7d4d9.e1d00b4","name":"Number","env":[],"ui":{"params":[{"id":1,"name":"V","label":"Input V:","labels":{"en-US":"Input V:"},"type":"num","value":""}]},"ui_in":{"1":{"name":"V","type":"num","value":"3.14"}},"x":380,"y":260,"wires":[["548a2d1d.0e7094"]]},{"id":"30c0445c.59fcdc","type":"inject","z":"7d7d4d9.e1d00b4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":320,"wires":[["12a80ee6.5045d1"]]},{"id":"50d90c53.dbc2b4","type":"debug","z":"7d7d4d9.e1d00b4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":530,"y":320,"wires":[]},{"id":"12a80ee6.5045d1","type":"subflow:9cd15433.4d8a48","z":"7d7d4d9.e1d00b4","name":"Bool","env":[],"ui":{"params":[{"id":1,"name":"V","label":"Input V:","labels":{"en-US":"Input V:"},"type":"bool","value":"true"}]},"ui_in":{"1":{"name":"V","type":"bool","value":"false"}},"x":370,"y":320,"wires":[["50d90c53.dbc2b4"]]},{"id":"ac9b3bde.279568","type":"inject","z":"7d7d4d9.e1d00b4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":380,"wires":[["c9c3bced.18afa"]]},{"id":"1329e15b.21ecbf","type":"debug","z":"7d7d4d9.e1d00b4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":530,"y":380,"wires":[]},{"id":"c9c3bced.18afa","type":"subflow:9cd15433.4d8a48","z":"7d7d4d9.e1d00b4","name":"JSON","env":[],"ui":{"params":[{"id":1,"name":"V","label":"Input V:","labels":{"en-US":"Input V:"},"type":"str","value":""}]},"ui_in":{"1":{"name":"V","type":"str","value":"{\"X\":0,\"Y\":1}"}},"x":370,"y":380,"wires":[["1329e15b.21ecbf"]]},{"id":"330ad88e.cc24c8","type":"inject","z":"7d7d4d9.e1d00b4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":440,"wires":[["6570b6d4.d83468"]]},{"id":"3c64bb73.fea264","type":"debug","z":"7d7d4d9.e1d00b4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":530,"y":440,"wires":[]},{"id":"6570b6d4.d83468","type":"subflow:9cd15433.4d8a48","z":"7d7d4d9.e1d00b4","name":"Buffer","env":[],"ui":{"params":[{"id":1,"name":"V","label":"Input V:","labels":{"en-US":"Input V:"},"type":"bin","value":""}]},"ui_in":{"1":{"name":"V","type":"bin","value":"[70,79,79]"}},"x":370,"y":440,"wires":[["3c64bb73.fea264"]]},{"id":"a45febfa.f335a8","type":"inject","z":"7d7d4d9.e1d00b4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":500,"wires":[["a74c4b40.1fb3c8"]]},{"id":"9cf03cbc.21121","type":"debug","z":"7d7d4d9.e1d00b4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":530,"y":500,"wires":[]},{"id":"a74c4b40.1fb3c8","type":"subflow:9cd15433.4d8a48","z":"7d7d4d9.e1d00b4","name":"Env","env":[],"ui":{"params":[{"id":1,"name":"V","label":"Input V:","labels":{"en-US":"Input V:"},"type":"env","value":""}]},"ui_in":{"1":{"name":"V","type":"env","value":"HOME"}},"x":370,"y":500,"wires":[["9cf03cbc.21121"]]},{"id":"50bfbed6.b6e98","type":"inject","z":"7d7d4d9.e1d00b4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":560,"wires":[["59034784.6f2f88"]]},{"id":"c858ac7f.8dec4","type":"debug","z":"7d7d4d9.e1d00b4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":530,"y":560,"wires":[]},{"id":"59034784.6f2f88","type":"subflow:9cd15433.4d8a48","z":"7d7d4d9.e1d00b4","name":"Checkbox","env":[],"ui":{"params":[{"id":1,"name":"V","label":"Check V","labels":{"en-US":"Check V"},"type":"checkbox","value":"true"}]},"ui_in":{},"x":390,"y":560,"wires":[["c858ac7f.8dec4"]]},{"id":"232f6165.c654de","type":"inject","z":"7d7d4d9.e1d00b4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":620,"wires":[["30942a38.460416"]]},{"id":"80012e5.50121d","type":"debug","z":"7d7d4d9.e1d00b4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":530,"y":620,"wires":[]},{"id":"30942a38.460416","type":"subflow:9cd15433.4d8a48","z":"7d7d4d9.e1d00b4","name":"Spinner","env":[],"ui":{"params":[{"id":1,"name":"V","label":"Input V:","labels":{"en-US":"Input V:"},"type":"spinner","value":"10"}]},"ui_in":{"1":{"name":"V","type":"spinner","value":8}},"x":380,"y":620,"wires":[["80012e5.50121d"]]},{"id":"edb301aa.60977","type":"inject","z":"7d7d4d9.e1d00b4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":680,"wires":[["fa5904f5.aa2fb8"]]},{"id":"6d380160.d150a","type":"debug","z":"7d7d4d9.e1d00b4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":530,"y":680,"wires":[]},{"id":"fa5904f5.aa2fb8","type":"subflow:9cd15433.4d8a48","z":"7d7d4d9.e1d00b4","name":"Menu","env":[],"ui":{"params":[{"id":1,"name":"V","label":"Input V:","labels":{"en-US":"Input V:"},"type":"menu","value":"","items":[{"value":"Item0","values":{"en-US":"Item0"}},{"value":"Item1","values":{"en-US":"Item1"}}]}]},"ui_in":{"1":{"name":"V","type":"menu","value":"Item0"}},"x":370,"y":680,"wires":[["6d380160.d150a"]]},{"id":"bafe285b.83ce58","type":"inject","z":"7d7d4d9.e1d00b4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":740,"wires":[["ccc5f57c.ef3098"]]},{"id":"c8661f11.b9c16","type":"debug","z":"7d7d4d9.e1d00b4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":530,"y":740,"wires":[]},{"id":"ccc5f57c.ef3098","type":"subflow:9cd15433.4d8a48","z":"7d7d4d9.e1d00b4","name":"Menu (i18n)","env":[],"ui":{"params":[{"id":1,"name":"V","label":"Input V:","labels":{"ja":"Vを入力","en-US":"Input V:"},"type":"menu","value":"","items":[{"value":"Item0","values":{"ja":"項目0","en-US":"Item0"}},{"value":"Item1","values":{"ja":"項目1","en-US":"Item1"}}]}]},"ui_in":{"1":{"name":"V","type":"menu","value":"Item1"}},"x":390,"y":740,"wires":[["c8661f11.b9c16"]]},{"id":"ee1f7dd5.8b0c3","type":"inject","z":"7d7d4d9.e1d00b4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":800,"wires":[["744ce864.e35688"]]},{"id":"a8786715.9d8568","type":"debug","z":"7d7d4d9.e1d00b4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":530,"y":800,"wires":[]},{"id":"744ce864.e35688","type":"subflow:9cd15433.4d8a48","z":"7d7d4d9.e1d00b4","name":"Label","env":[],"ui":{"params":[{"id":1,"name":"V","label":"Label","labels":{"ja":"ラベル","en-US":"Label"},"type":"label","value":""}]},"ui_in":{},"x":370,"y":800,"wires":[["a8786715.9d8568"]]},{"id":"84a04eb1.a4bf3","type":"inject","z":"7d7d4d9.e1d00b4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":860,"wires":[["41edff34.43838"]]},{"id":"208fc9a1.a59e76","type":"debug","z":"7d7d4d9.e1d00b4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":550,"y":860,"wires":[]},{"id":"f239757.0961188","type":"inject","z":"7d7d4d9.e1d00b4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":920,"wires":[["c840cdae.51257"]]},{"id":"106fe680.76eeca","type":"debug","z":"7d7d4d9.e1d00b4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":530,"y":920,"wires":[]},{"id":"c840cdae.51257","type":"subflow:9cd15433.4d8a48","z":"7d7d4d9.e1d00b4","name":"Any","env":[],"ui":{"params":[{"id":1,"name":"V","label":"Input V:","labels":{"ja":"Input V:"},"type":"any","value":"","items":["str","num","bool","json","bin","env"]}]},"ui_in":{"1":{"name":"V","type":"any","value_type":"env","value":"HOME"}},"x":370,"y":920,"wires":[["106fe680.76eeca"]]},{"id":"41edff34.43838","type":"subflow:9cd15433.4d8a48","z":"7d7d4d9.e1d00b4","name":"Label (HTML)","env":[],"ui":{"params":[{"id":1,"name":"","label":"<i class=\"fa fa-spinner fa-spin\"/> <b>HTML</b> Label","labels":{"en-US":"<i class=\"fa fa-spinner fa-spin\"/> <b>HTML</b> Label"},"type":"str","value":""}]},"ui_in":{},"x":400,"y":860,"wires":[["208fc9a1.a59e76"]]},{"id":"cdb6d488.698ec8","type":"inject","z":"2e434a18.e7c0a6","name":"","topic":"","payload":"Hello World!","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":190,"y":120,"wires":[["29fcfbd2.77f394","a0ad481f.7f4af8"]]},{"id":"b127047b.47aca8","type":"debug","z":"2e434a18.e7c0a6","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":550,"y":120,"wires":[]},{"id":"3858208a.5b441","type":"inject","z":"7d7d4d9.e1d00b4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":140,"wires":[["1307ee65.8192e2"]]},{"id":"19159321.bcd12d","type":"debug","z":"7d7d4d9.e1d00b4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":530,"y":140,"wires":[]},{"id":"1307ee65.8192e2","type":"subflow:9cd15433.4d8a48","z":"7d7d4d9.e1d00b4","name":"String","env":[],"ui":{"params":[{"id":1,"name":"V","label":"Input V:","labels":{"en-US":"Input V:"},"type":"str","value":""}]},"ui_in":{"1":{"name":"V","type":"str","value":"ABC"}},"x":370,"y":140,"wires":[["19159321.bcd12d"]]},{"id":"f8be69e5.5f64e8","type":"switch","z":"4d6926d3.28e678","name":"","property":"$env(\"MODE\")","propertyType":"jsonata","rules":[{"t":"cont","v":"Upper","vt":"str"},{"t":"cont","v":"Lower","vt":"str"},{"t":"else"}],"checkall":"true","repair":false,"outputs":3,"x":190,"y":160,"wires":[["47f27b59.4f1ff4"],["86de1873.9dccd8"],[]]},{"id":"47f27b59.4f1ff4","type":"change","z":"4d6926d3.28e678","name":"To Uppercase","rules":[{"t":"set","p":"payload","pt":"msg","to":"$uppercase(payload)\t","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":380,"y":80,"wires":[[]]},{"id":"86de1873.9dccd8","type":"change","z":"4d6926d3.28e678","name":"To Lowercase","rules":[{"t":"set","p":"payload","pt":"msg","to":"$lowercase(payload)\t","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":380,"y":140,"wires":[[]]},{"id":"29fcfbd2.77f394","type":"subflow:4d6926d3.28e678","z":"2e434a18.e7c0a6","name":"","env":[],"ui":{"params":[]},"ui_in":{"2":{"name":"MODE","type":"menu","value":"To Upper"}},"x":380,"y":120,"wires":[["b127047b.47aca8"]]},{"id":"a0ad481f.7f4af8","type":"subflow:4d6926d3.28e678","z":"2e434a18.e7c0a6","name":"","env":[],"ui":{"params":[]},"ui_in":{"2":{"name":"MODE","type":"menu","value":"To Lower"}},"x":380,"y":180,"wires":[["57c509bd.d238d8"]]},{"id":"57c509bd.d238d8","type":"debug","z":"2e434a18.e7c0a6","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":550,"y":180,"wires":[]},{"id":"7ce31917.996308","type":"inject","z":"abe77105.3c0e9","name":"","topic":"","payload":"This-is-a-pen","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":190,"y":100,"wires":[["c1b1724b.a7d8d"]]},{"id":"1a2df262.fdc08e","type":"debug","z":"abe77105.3c0e9","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":590,"y":100,"wires":[]},{"id":"fe283731.cfb608","type":"function","z":"9dd21fb1.c72ce","name":"","func":"var old_str = env.get(\"OLD_STR\");\nvar new_str = env.get(\"NEW_STR\");\nvar ignore_case = env.get(\"IGNORE_CASE\");\nvar opt = \"g\";\nif (ignore_case) {\n    opt = opt +\"i\";\n}\nmsg.payload = msg.payload.replace(new RegExp(old_str, opt), new_str);\nreturn msg;","outputs":1,"noerr":0,"x":200,"y":80,"wires":[[]]},{"id":"c1b1724b.a7d8d","type":"subflow:9dd21fb1.c72ce","z":"abe77105.3c0e9","name":"","env":[],"ui":{"params":[]},"ui_in":{"2":{"name":"OLD_STR","type":"str","value":"-"},"3":{"name":"NEW_STR","type":"str","value":","},"4":{"name":"IGNORE_CASE","type":"checkbox","value":true}},"x":400,"y":100,"wires":[["1a2df262.fdc08e"]]},{"id":"94d0bf56.fefae","type":"inject","z":"abe77105.3c0e9","name":"","topic":"","payload":"John Smith","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":190,"y":160,"wires":[["cbbd908c.bcf9e"]]},{"id":"19293299.7880ed","type":"debug","z":"abe77105.3c0e9","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":590,"y":160,"wires":[]},{"id":"cbbd908c.bcf9e","type":"subflow:9dd21fb1.c72ce","z":"abe77105.3c0e9","name":"","env":[],"ui":{"params":[]},"ui_in":{"2":{"name":"OLD_STR","type":"str","value":"(\\w+)\\s(\\w+)"},"3":{"name":"NEW_STR","type":"str","value":"$2, $1"},"4":{"name":"IGNORE_CASE","type":"checkbox","value":false}},"x":400,"y":160,"wires":[["19293299.7880ed"]]}]
```

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [x] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by HiroyasuNishiyama** [comment]
Updated UI for defining env var UI.

Example: (API key for openweathermap shoud be specified.)
```
[{"id":"3fd26238.041b7e","type":"subflow","name":"weather","info":"# Wether Node\n\n## Input\n\n- *payload*: city name\n\n## Output\n\n- *payload*: current weather\n\n## Description\n\nGet current weather of specified city using OpenWeather API.","category":"","in":[{"x":40,"y":80,"wires":[{"id":"73c843a0.1efcec"}]}],"out":[{"x":760,"y":80,"wires":[{"id":"4bda19ec.de4488","port":0},{"id":"fb07ce06.e57aa","port":0}]}],"env":[{"name":"","ui":{"open":true,"hasUI":true,"icon":"font-awesome/fa-rocket","labels":{"en-US":"Config"},"type":"hidden","inputTypes":{"str":true,"num":true,"bool":true,"json":true,"bin":true,"env":true},"menu":[]}},{"name":"APIKEY","type":"str","value":"","ui":{"open":true,"hasUI":true,"icon":"font-awesome/fa-key","labels":{"en-US":"API Key"},"type":"input","inputTypes":{"str":true,"num":false,"bool":false,"json":false,"bin":false,"env":true},"menu":[]}},{"name":"ALLMSG","type":"bool","value":"true","ui":{"open":true,"hasUI":true,"icon":"","labels":{"en-US":"send all info"},"type":"checkbox","inputTypes":{"str":true,"num":true,"bool":true,"json":true,"bin":true,"env":true},"menu":[]}}],"icon":"font-awesome/fa-cloud"},{"id":"72d809d1.3b0df8","type":"http request","z":"3fd26238.041b7e","name":"get weather ","method":"GET","ret":"obj","paytoqs":false,"url":"http://api.openweathermap.org/data/2.5/weather?q={{topic}}&APPID={{APIKEY}}","tls":"","proxy":"","authType":"basic","x":210,"y":140,"wires":[["fb07ce06.e57aa"]]},{"id":"4bda19ec.de4488","type":"change","z":"3fd26238.041b7e","name":"set result","rules":[{"t":"set","p":"payload","pt":"msg","to":"payload.weather[0].description","tot":"jsonata"},{"t":"set","p":"am","pt":"msg","to":"ALLMSG","tot":"env"}],"action":"","property":"","from":"","to":"","reg":false,"x":620,"y":180,"wires":[[]]},{"id":"73c843a0.1efcec","type":"change","z":"3fd26238.041b7e","name":"set params","rules":[{"t":"set","p":"APIKEY","pt":"msg","to":"APIKEY","tot":"env"},{"t":"set","p":"topic","pt":"msg","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":170,"y":80,"wires":[["72d809d1.3b0df8"]]},{"id":"fb07ce06.e57aa","type":"switch","z":"3fd26238.041b7e","name":"select result type","property":"ALLMSG","propertyType":"env","rules":[{"t":"true"},{"t":"else"}],"checkall":"false","repair":false,"outputs":2,"x":410,"y":140,"wires":[[],["4bda19ec.de4488"]]},{"id":"d06a2e07.6915d","type":"comment","z":"3fd26238.041b7e","name":"Get weather from openweathermap API","info":"","x":170,"y":20,"wires":[]},{"id":"6657750f.a305ac","type":"tab","label":"Weather","disabled":false,"info":""},{"id":"c069392e.2feef8","type":"inject","z":"6657750f.a305ac","name":"","topic":"","payload":"London","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":130,"y":200,"wires":[["b75e3ee.ededfc"]]},{"id":"cbd5b937.f105c8","type":"debug","z":"6657750f.a305ac","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":490,"y":200,"wires":[]},{"id":"31b97b53.aa7134","type":"inject","z":"6657750f.a305ac","name":"","topic":"","payload":"Tokyo","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":130,"y":260,"wires":[["b75e3ee.ededfc"]]},{"id":"b75e3ee.ededfc","type":"subflow:3fd26238.041b7e","z":"6657750f.a305ac","name":"","env":[{"name":""},{"name":"ALLMSG","type":"bool","value":"false"}],"x":320,"y":200,"wires":[["cbd5b937.f105c8"]]},{"id":"614fe7a8.8a4388","type":"inject","z":"6657750f.a305ac","name":"","topic":"","payload":"Winchester,uk","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":140,"wires":[["b75e3ee.ededfc"]]}]
```

**Comment by knolleary** [comment]
Some proposed changes for the UI. My concern is the properties list is less than half the available space in the dialog, which does not give the user much room once they start defining UI elements.

image


1. Move ‘Category’ to the Appearance tab
2. Move ‘There are 2 instances’ message into the dialog footer – consistent with Config node edit dialog
3. Move ‘Preview UI’ button to bottom right of list.
4. Rename ‘Env var’ to ‘Subflow properties’ or just ‘Properties’
5. Either:
    - Remove UI Language from this PR. We can add it back later when we consider the design for i18n of node description as well. 
    - Move it as a select box next to the preview button

**Comment by HiroyasuNishiyama** [comment]
Thank you for review!
(1) and (2): opened new PR on these items (https://github.com/node-red/node-red/pull/2229).
(3): my concern on this is moving preview button to bottom requires preview OK button move to bottom.  
(4): change to "Subflow properties" because "Properties" is used as tab name
(5): will creates fixes based on one of suggested approaches

**Comment by dceejay** [comment]
could (3) be a smaller button to right on same row as the Subflow Properties label ?

**Comment by HiroyasuNishiyama** [comment]
I think it will be possible.

**Comment by dceejay** [comment]
I think that would meet the objectives of taking up no more  space, allowing you to toggle between edit and preview modes without moving the mouse, and de-emphasizing the language menu.

**Comment by HiroyasuNishiyama** [comment]
Thank you!  I will try to create fix based on your suggestion.

**Comment by dceejay** [comment]
random Q - Now that we also have node enable indicator bottom left bar - where would the "number of instances" info sit ? to the right ? / left ?
image

**Comment by HiroyasuNishiyama** [comment]
The node enable control  can not be applied to subflow template.  So, we can use whole area of footer.  The number info sit to the left.

スクリーンショット 2019-07-11 23 24 15

**Comment by HiroyasuNishiyama** [comment]
fixed (3), (4), and (5).

**Comment by knolleary** [comment]
Thanks. I am currently reviewing the UI design of the individual rows in the property table. I am still not happy with the user experience. I am going to work on this over the weekend and will have something to share then.

**Comment by knolleary** [comment]
Now that #2236 is merged, all of the commits from this PR have been merged. This PR is not needed anymore.

**Pull request closed without merging**
