### PR TITLE
Update i18next dependency.

### PR DESCRIPTION
**Pull request by WilliamRClark**
- [X ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

Security vulnerability in third party library:

Prototype Pollution Vulnerability in i18next library - @see: https://snyk.io/vuln/SNYK-JS-I18NEXT-1065979

## Checklist

- [X ] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ X] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by knolleary** [comment]
Thanks for this. Our unit tests do not cover the editor functionality. What manual testing have you done to verify this works as expected? It's jumping 4 major version changes - something that always makes me nervous 😄

**Comment by knolleary** [comment]
Also please remove `package-lock.json`.

**Comment by WilliamRClark** [comment]
prEditor

This is the localization package.  I've verified that the editor still comes up with English resources after my changes.

**Comment by knolleary** [comment]
The change you propose will work for the runtime side of things, but not the editor.

For historic reasons, the editor code has its own internal copy of `i18next.min.js` in the src tree (under the vendor directory). This is an old back level version. I have just tried updating it to the latest and hit a number of breaking changes.

This is going to take some time to sort out properly - including changing the build to pull `i18next.min.js` from the npm installed version to ensure it is kept current in the future.

Not going to hold up the 1.3 release for this today - but will make it high priority for 1.3.1.

**Comment by knolleary** [comment]
This has been addressed for the 2.0 release in #2940

**Pull request closed without merging**
