### PR TITLE
Update 21-httpin.js

### PR DESCRIPTION
**Pull request by lingej**
Allow method PATCH so we will be able to send JSON payload to pimatics REST API

### CODE REVIEW

**Comment by knolleary** [comment]
Hi, thanks for this.

As described in the contribution guidelines, we require a signed contribution licence agreement before we can accept a pull request.

On the change itself, for completeness, PATCH should be added to the drop down list in the node's edit dialog.

**Comment by lingej** [comment]
@knolleary 

Hi Nick. Please ignore this pull request.

Joerg

**Comment by dceejay** [comment]
Should this be closed ? should we implement manually as it's a small update ? Is it required ?

**Comment by lingej** [comment]
IMHO: PATCH is a valid HTTP Request Methos and should be avaliable by default. But is will not sign a CLA for this small kind of change.

Joerg

**Comment by dceejay** [comment]
Thanks for the clarification.
We agree it may well be useful. So no problem - we will add the capability at this end.
Will leave open so we can track.

**Comment by dceejay** [comment]
Closed by applying fix manually

**Pull request closed without merging**
