### PR TITLE
Update 70-HTML for variable tag

### PR DESCRIPTION
**Pull request by rcruicks**
enable simple screen scraping through paired CSS+URL

### CODE REVIEW

**Comment by dceejay** [comment]
Hi, what does this actually do re http ? Why should this be in this node and not a change node before?

**Comment by rcruicks** [comment]
current html node only support static CSS - so can only be used to extract same content from any incoming page with the same/common structure - change node can't affect the selector.  for programmatic screenscraping-type operations, the html node could be used to extra URL-specific content via an associated URL-specific selector, allowing for more flexibility to extra common data froma variety of sources

**Comment by dceejay** [comment]
ok. got it now. We would need a CLA in order to accept this as a PR - but as it's a simple change I'm happy to apply manually if that's ok with you ?

**Comment by rcruicks** [comment]
aha - OK by me.

**Pull request closed without merging**
