### PR TITLE
function node changes

### PR DESCRIPTION
**Pull request by yehudita**
The pull request is about https://github.com/node-red/node-red/commit/509eed1c22718e7d848dcda751ef27504bb2eb5b commit.
When I open function node, and close without changes.
The node is marked as changed.

### CODE REVIEW

**Comment by knolleary** [comment]
This fix has been on the todo list for a while.

This PR has included the multiple-close changes that we fixed a while ago - if you want us to pick up this change, you'll need to rebase the fix on master and remove your other commit.

And as with your previous pull-requests, we still need a signed CLA before we can accept these changes.

Let me know if you want to proceed, otherwise I'll jump in and fix this (along with a couple other issues with the function node that are related).

**Comment by yehudita** [comment]
The pull request is about https://github.com/node-red/node-red/commit/509eed1c22718e7d848dcda751ef27504bb2eb5b commit.
not about multiple-close

**Comment by knolleary** [comment]
Yes, but your pull request includes both 509eed1 and 75f49be. We cannot merge this pull-request whilst it contains both commits.

**Comment by yehudita** [comment]
You can add my fixing, manually

**Comment by dceejay** [comment]
Thanks

**Pull request closed without merging**
