### PR TITLE
Add node installation from other than public site

### PR DESCRIPTION
**Pull request by KazuhiroItoh**
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes

This PR proposes the addition of more convenient and simple functions for node installation from other than public site.
Details are written in [design note](https://github.com/node-red/designs/blob/master/designs/node-installation/node-installation.md).

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [x] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by knolleary** [comment]
Please add a link to the design note. Thanks

**Comment by KazuhiroItoh** [comment]
Please refer to the following URL.
https://github.com/node-red/designs/blob/master/designs/node-installation/node-installation.md

**Comment by knolleary** [comment]
Looks good. Thanks.

One extra thought for later on is whether the view of available packages should give some visual indication as to where the package is coming from. For example an icon that when hovered over shows a tooltip with that information.

image

**Comment by mannharleen** [comment]
@KazuhiroItoh  The URL is broken. Should be https://github.com/node-red/designs/blob/master/designs/node-installation/README.md

**Pull request merged**
