### PR TITLE
Initial support of merge & reduce mode for JOIN node

### PR DESCRIPTION
**Pull request by HiroyasuNishiyama**
## Before you hit that Submit button....

Please read our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
before submitting a pull-request.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

If you want to raise a pull-request with a new feature, or a refactoring
of existing code, it **may well get rejected** if it hasn't been discussed on
the [mailing list](https://groups.google.com/forum/#!forum/node-red) or
[slack team](https://nodered.org/slack) first.

## Proposed changes

This PR adds support of new merge mode and reduce mode for JOIN node including:

- reducing message sequence represented by parts property with JSONata expressions,
- merging incoming messages using topic value.

## Checklist
_Put an `x` in the boxes that apply_

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [x] I have added suitable unit tests to cover the new/changed functionality

## Example Flows

[flow.txt](https://github.com/node-red/node-red/files/1618600/flow.txt)

### CODE REVIEW

**Comment by HiroyasuNishiyama** [comment]
Hi, fixed following problems:
- order of modes in menu,
- add default entry in merge mode,
- reconfigure TypedInput fields after mode selection,
- add more description on "reduce right",
- typo in doc.

I'll try to make reduce functionality in manual mode later.

**Comment by dceejay** [comment]
Agree - let's get this in first then look at reduce in manual mode.
Final question - In reduce mode - could the fixup expression being blank be a valid input ?
image

**Comment by HiroyasuNishiyama** [comment]
Yes.  If *Fixup exp* is empty, it means no fixup application.

By the way, I found a problem of manual mode node setting while creating the above fix.

join03

Type selector do not appear after mode selection.  Similar problem was also in reduce mode and fixed by above commit.  I'll make fix on this later.

**Comment by bigmonkeyboy** [comment]
Ok - great.
Yes - I was just wondering why it was outlined in red (error) ?

**Comment by HiroyasuNishiyama** [comment]
I think red line means that empty string is not valid JSONata expression.
I'd like to know if there is any possible work around on it.

**Comment by HiroyasuNishiyama** [comment]
Made JSONata expression field to allow empty string (i.e. no red border).
join04

**Comment by HiroyasuNishiyama** [comment]
Fixed a typo in message catalog: sort node -> join node

**Pull request merged**
