### PR TITLE
Add option to deep-clone properties in Change node

### PR DESCRIPTION
**Pull request by knolleary**
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes

A common gotcha with the Change node is that when setting object properties it doesn't clone the value - so you end up with a reference to the original property. Any modifications to the 'new' property also applies to the original one. This happens with  both setting from a msg property and context property.

This PR adds an option to the 'set' action of the Change node to make a 'deep copy' of the value. 

The option is only shown for the 'set' rule when the 'source' is `msg` `flow` `global` or `env` - as those are the ones that can set a value that could be referenced elsewhere.

I have also changed the text of the `set` rule - where it used to just say `to` it now says `to the value` which hopefully helps make it clearer the 'direction' of the action.

image

This will also help address #3144 

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [x] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
Hi Nick, 

It's hard to see from the PR on my mobile. It this a per entry option?

If not, I wonder if it might be more suitable to offer this per item.  E.g. add `"clone"` to the drop-down list along side copy, move, delete etc.

**Comment by knolleary** [comment]
As described, yes, it is per entry.
> The option is only shown for the 'set' rule when the 'source' is msg flow global or env - as those are the ones that can set a value that could be referenced elsewhere.

**Comment by Steve-Mcl** [comment]
Ah, perfect. 

☺️ embarrassed to say I missed that in the description - sorry.

**Comment by thechane** [comment]
Can I suggest also adding a deep clone option to the split node to fully address [#3144](https://github.com/node-red/node-red/issues/3144).

**Comment by knolleary** [comment]
> Can I suggest also adding a deep clone option to the split node to fully address

The issues in #3144 come from the Change node behaviour, not the Split node.

The Split already does clone the message as needed - but if you pass it a message with cross-property references, then the split message will also have cross-property references within the message.

**Pull request merged**
