### PR TITLE
TCPGet: Ensure done() is called only once

### PR DESCRIPTION
**Pull request by natcl**

### CODE REVIEW

**Comment by dceejay** [comment]
There is extra console.log left in :-)

**Comment by natcl** [comment]
Hmm I can't seem to find it ?

**Comment by natcl** [comment]
Oh you mean the commented ones ? I believe they were there before the multi-client changes but I can remove them, let me know.

**Comment by dceejay** [comment]
@natcl aah - yes - perils of looking at code on a phone.... line wrap split the line just at the //  looked like a new line.. - apologies !.

**Pull request merged**
