### PR TITLE
rework of DE translation

### PR DESCRIPTION
**Pull request by heikokue**
- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes
complete rework of the german (DE) translation of the editor-client, runtime and nodes

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by knolleary** [comment]
We're aiming to get 1.3-beta released by the end of next week. Let me know if this PR is likely to be ready or not for then.

**Comment by knolleary** [comment]
Hi @heikokue - any updates on this PR?

**Comment by heikokue** [comment]
Hello Nick, the core translation is still ongoing, but I'm on the home straight.
editor-client and runtime locales are ready for review.
the core's nodes are 90% reworked.
till now I spent over 50 hours and I hope I can finish it till end of this month.
I do not only translate text files, I also check it live in node-red, that it fits in the dialogs and the appearance (HTML rendering) is correct and uniform.
There were many strange translation mistakes.
up to now the community's support to review it and give feedback is quite small...

**Comment by heikokue** [comment]
Hello together, I just finished and pushed my rework of the german translation of the core (editor, runtime, jsonata and the core-nodes). Now it's on you to review it, please!
There you can find further infos: https://discourse.nodered.org/t/german-translation-anyone-interested/38209/5
The translation is on the level of NR-version 1.2.9
Later/ongoing developments (e.g. MQTT5) are not yet translated. I like to wait till the next release.
I hope, you enjoy it. And if not, please enter an issue at https://github.com/heikokue/node-red

**Comment by knolleary** [comment]
We have no way of reviewing your changes. I assume you have been reviewing them with other German users on slack?

**Comment by heikokue** [comment]
hello nick, early parts are discussed. the last changes still need to be reviewed.

**Comment by heikokue** [comment]
How to continue with this PR?
Split into smaller chunks? And how?
A split will be sometimes not sensible because of common used files, e.g.:
- editor-client\locales\de\editor.json (has all editor UI translations)
- nodes\locales\de\messages.json (has all core-node translations)
If we split it node by node, we will need many PRs and the merges has to be done one after another.

**Comment by dceejay** [comment]
Hi,
yes these would be hard to split. So really this does just need a review by a 2nd person. (German user). You said that some had been discussed - any chance you can push forward the rest ?

**Comment by heikokue** [comment]
As you can see in slack #i18n-de, the response is quite low and in the last weeks zero.
I will split this PR in parts as sensible (which will still bigger).

**Comment by knolleary** [comment]
There is no benefit to now splitting this in to smaller PRs unless there is someone ready to review the individual PRs.

At this point, lets just merge this PR as-is. If there are problems, then the DE community can raise issues/prs to fix.

**Comment by heikokue** [comment]
Cool, thanks! I also like a pragmatic approach ;-)
You are welcome to pass on DE-specific issues and PRs to me in the future and I can moderate it on the forum or Slack and do reviews.

**Pull request merged**
