### PR TITLE
Use a more subtle border on the header

### PR DESCRIPTION
**Pull request by bonanitech**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

As discussed [on the forum](https://discourse.nodered.org/t/can-we-have-a-more-subtle-border-on-the-header/89043), I'm proposing to use a color that makes the header border more subtle. I used the same red from the Deploy button.

Now:

SCR-20240628-jads<br>

Then:

SCR-20240628-jaif<br>

It also works well with themes. Here's an example using the 'dark' theme.

Now:

SCR-20240628-jbra<br>

Then:

SCR-20240628-jbtn<br>

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ ] I have run `npm run test` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by bonanitech** [comment]
Why did the tests fail? I swear I didn't change anything other than the border color. 🙂

**Comment by knolleary** [comment]
We have an occasional test failure due to a timing issue - won't be related to your proposed changes (obviously... :)

The original intent was to make the border less subtle. This PR makes it very subtle - almost unnoticeable. I don't want to keep bouncing between the two.

I think it should probably be somewhere in between the two.

**Comment by bonanitech** [comment]
This one uses the same red (#D12B2B) from the FlowFuse themes.

image

It's not as bright as the original nor as dark as my previous proposal. What do you think?

**Comment by bonanitech** [comment]
Do you think this looks better? It's a little bit darker than the original. But not as dark as the one I originally proposed.

Now:

SCR-20240628-jads<br>

Then:

image<br>

**Comment by knolleary** [comment]
@bonanitech to be honest, I'm struggling to tell the difference between the last two screenshots. I've not seen any additional commits to the branch so I'm not sure what colour you are proposing for me to check it out locally.

**Comment by knolleary** [comment]
Thanks for the update. It is a *very* subtle difference. I've no objection to tweaking it - do you think this works better for the dark themes by default?

**Comment by bonanitech** [comment]
Thanks, @knolleary.

It does work better for dark themes. But it also works better with the default one, in my opinion.

**Pull request merged**
