### PR TITLE
Clear context contents when switching projects

### LINKED ISSUE #3240: Problem with context variables
### Current Behavior

When changing project the global context variables are kept for the new project.

### Expected Behavior

Delete the context variables from another project.

### Steps To Reproduce

1. Create a project.
2. Define global context variables.
3. Create another project.
4. Update the global context.

The context variables of the previous project are maintained.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 2.1.3
- Node.js version: v12.22.6
- npm version: 6.14.15
- Platform/OS: Rasperry Pi/Raspbian
- Browser: Chrome

### PR DESCRIPTION
**Pull request by knolleary**
- [x] New Feature

Whilst originally treated as a bug fix, the ongoing conversation in #3240 has made the valid point that clearing context across project switches is not always desirable.

This needs to be an optional behaviour.

### CODE REVIEW

**Comment by knolleary** [comment]
Put back to Draft status as we need to make this behaviour optional. See #3240 discussion for rationale.

**Comment by dceejay** [comment]
Just to clarify - which mode will be the default going forwards ? To clear or not to clear ?

**Comment by knolleary** [comment]
There will be a checkbox in the Open Project dialog to choose whether to clear context or not. Whether it is ticked by default or not is open for discussion.

That said, the underlying (internal, unpublished) API will default to clearing unless the API request says otherwise.

My personal preference would be for the checkbox to be ticked by default (clear context) because that fits my mental model of how I user projects. But others may disagree and I'm open to the discussion

**Comment by dceejay** [comment]
I would agree with clearing by default, as that has less chance of leaking security/session info from one project to another.

**Comment by knolleary** [comment]
I've now added a checkbox to the Open Project dialog to select whether to clear context or not - by default it is checked.

**Comment by knolleary** [comment]
@kazuhitoyokoi another message update - https://github.com/node-red/node-red/pull/3243/files#diff-1653147965c86b32c5ec95ba8fe727a71b12dac624b246d912cd2d1529421ccbR1097

**Pull request merged**
