### PR TITLE
Subflow: Add labels to OUTPUT nodes

### PR DESCRIPTION
**Pull request by ralphwetzel**
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes
[Subflow: Add labels to OUTPUT nodes](https://discourse.nodered.org/t/subflow-add-labels-to-output-nodes/56266)

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by knolleary** [comment]
Looks good. If I'm going to be very picky, in your screenshot, the left-hand text on Output 3 and 4 is not vertically aligned in the same way as Output 1 and 2 are.

image

**Comment by knolleary** [comment]
I'm going to merge this with some tweaks applied to resolve the vertical alignment.

Thanks for the contribution!

**Comment by ralphwetzel** [comment]
Hi Nick!
You're right. That was a deliberated design decision.
For single line labels (or the case without label), I sticked to the layout of the given Output node.
As soon as there's enough vertical space (beginning w/ a two line name), I centered the number and the port - which looked better to me.

image

Feel free to adapt this as appropriate.
R.

**Comment by knolleary** [comment]
Thanks for the comment. On balance, it looked odd to me for the alignment to not match. I've merged #3370 that keeps them all aligned. We can of course iterate in the future. 👍🏻

**Pull request merged**
