### PR TITLE
Add RFC4180 compliant mode to CSV node

### PR DESCRIPTION
**Pull request by Steve-Mcl**
## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

Implements a new RFC compliant mode to the CSV node for NR V4

### Highlights
* Maintains legacy processing for backwards compatibility
   * This is via the addition of a `Specification` drop down
   * Includes a `form-tip` warning beneath when legacy mode is selected - the intention is to remove legacy mode at some future time, this tip is there to encourage users to update their flows.
* Always* outputs RFC compliant CSV
   * \*we still permit line endings to be non-standard `\r` or `\n`
* Adds catchable error handling and node status (permitting user to intercept bad data)
* 13% faster or more in all cases tested so far

### Outline

The CSV node in its current form can output non RFC compliant CSV strings and can in some cases, incorrectly parses RFC compliant CSV strings.  A simple but definitive test is: given any RFC Compliant CSV string, we should be able to convert it to an `Object[]` then that `Object[]`, when passed through a 2nd CSV node, should convert back to the exact original input CSV.

There are several cases where this is not the case.

Below are 2 examples of this.  In a follow up post, I will add my full suite of test flows, complete with assertions and expected results.  Also includes performance measuring.

#### Example: where CSV node fails to correctly parse RFC compliant input
image

```json
[{"id":"fb90d993b5466b3c","type":"subflow","name":"Expect","info":"","category":"function","in":[{"x":80,"y":160,"wires":[{"id":"b7d75d6fb82e713b"}]}],"out":[{"x":450,"y":160,"wires":[{"id":"b7d75d6fb82e713b","port":0}]}],"env":[{"name":"property","type":"str","value":"payload","ui":{"icon":"font-awesome/fa-ellipsis-v","label":{"en-US":"Property"},"type":"input","opts":{"types":["str"]}}},{"name":"test","type":"str","value":"strictEqual","ui":{"icon":"font-awesome/fa-exclamation","label":{"en-US":"Test"},"type":"select","opts":{"opts":[{"l":{"en-US":"strictEqual"},"v":"strictEqual"},{"l":{"en-US":"deepStrictEqual"},"v":"deepStrictEqual"},{"l":{"en-US":"match"},"v":"match"},{"l":{"en-US":"notStrictEqual"},"v":"notStrictEqual"},{"l":{"en-US":"notDeepStrictEqual"},"v":"notDeepStrictEqual"},{"l":{"en-US":"doesNotMatch"},"v":"doesNotMatch"}]}}},{"name":"expected","type":"str","value":"","ui":{"icon":"font-awesome/fa-question-circle-o","label":{"en-US":"Expect"}}},{"name":"mode","type":"str","value":"throw","ui":{"icon":"font-awesome/fa-check-square","label":{"en-US":"Mode"},"type":"select","opts":{"opts":[{"l":{"en-US":"Throw on fail"},"v":"throw"},{"l":{"en-US":"Warn only"},"v":"dont-throw"}]}}}],"meta":{"module":"test-expected-payload","type":"test-expected-payload","version":"1.0.0","author":"Steve-Mcl","desc":"Test msg.expected vs msg.payload","keywords":"test,expected"},"color":"#C7E9C0","outputLabels":["msg"],"icon":"font-awesome/fa-file-code-o","status":{"x":420,"y":280,"wires":[{"id":"0082523530ce9a0d","port":0}]}},{"id":"b7d75d6fb82e713b","type":"function","z":"fb90d993b5466b3c","name":"test","func":"// let payload = cleanString(msg.payload)\n// let expected = cleanString(msg.expected || env.get('expected'))\nnode.status({fill:\"yellow\",shape:\"ring\",text:prefixTimeString(\"testing...\")});\n\nfunction prefixTimeString(str) {\n    const n = new Date();\n    const hours = String(n.getHours()).padStart(2, '0');\n    const minutes = String(n.getMinutes()).padStart(2, '0');\n    const seconds = String(n.getSeconds()).padStart(2, '0');\n    return `${hours}:${minutes}:${seconds}: ${str}`;\n}\n\nfunction cleanString(str) {\n    if (typeof str === \"object\") {\n        str = JSON.stringify(str)\n    }\n    if (typeof str !== \"string\") {\n        str = RED.util.ensureString(str)\n    }\n  const replacedString = str.replace(/\\r/g, \"\\\\r\").replace(/\\n/g, \"\\\\n\");\n  return replacedString;\n}\nconst dontThrow = env.get('mode') === 'dont-throw' // default is 'throw'\nconst prop = env.get(\"property\") || 'payload'\nlet payload = RED.util.getMessageProperty(msg,prop);\nif (typeof payload === 'string') {\n    payload = cleanString(payload)\n}\nlet expected = msg.expected || env.get('expected')\nif (typeof expected === 'string') {\n    expected = cleanString(expected)\n}\n\ntry {\n    const assersion = env.get(\"test\");\n    const test = assert[assersion]\n    if (!assersion || typeof test !== \"function\") {\n        throw new Error(`'${assersion}' is not a valid assertion`)\n    }\n\n    // node.warn({\n    //     assersion,\n    //     payload,\n    //     expected,\n    //     test\n    // })\n    test(payload, expected)\n\n    setTimeout(function() {\n        node.status({fill:\"green\",shape:\"ring\",text:prefixTimeString(\"pass\")});\n        node.send(msg)\n    }, 125);\n} catch (error) {\n    setTimeout(function() {\n        node.status({fill:\"red\",shape:\"dot\",text:prefixTimeString(\"fail\")});\n        const m2 = RED.util.cloneMessage(msg);\n        m2.expectedString = cleanString(expected)\n        m2.payloadString = cleanString(payload)\n        if (dontThrow) {\n            node.warn(error);\n            node.send(msg)\n        } else {\n            node.error(error, msg);\n            // throw error\n        }\n    }, 125);\n};\n","outputs":1,"timeout":0,"noerr":0,"initialize":"","finalize":"","libs":[{"var":"assert","module":"assert"}],"x":250,"y":160,"wires":[[]]},{"id":"0082523530ce9a0d","type":"status","z":"fb90d993b5466b3c","name":"","scope":["b7d75d6fb82e713b"],"x":270,"y":280,"wires":[[]]},{"id":"8268f21e6951c86c","type":"inject","z":"1b95bb0cab495f48","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":75,"y":580,"wires":[["9896243f8fcc7624"]],"l":false},{"id":"9896243f8fcc7624","type":"template","z":"1b95bb0cab495f48","name":"Valid CSV (LF in col c and in row 3)","field":"payload","fieldType":"msg","format":"handlebars","syntax":"mustache","template":"a'a,\"b,b\",\"c\"\"\nc\",d.d\na,b,c,\n,2,3,4\ni,j,l,\"m\nm\"\n\n","output":"str","x":260,"y":580,"wires":[["6c1d30cf764be856"]]},{"id":"6c1d30cf764be856","type":"csv","z":"1b95bb0cab495f48","name":"","spec":"","sep":",","hdrin":true,"hdrout":"all","multi":"mult","ret":"\\n","temp":"","skip":"0","strings":true,"include_empty_strings":false,"include_null_values":false,"x":170,"y":640,"wires":[["c7e4ced886d5fa0c"]]},{"id":"56d05067a729315d","type":"inject","z":"1b95bb0cab495f48","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":75,"y":1160,"wires":[["3175b64c8926a811"]],"l":false},{"id":"fd20062fe2b65617","type":"csv","z":"1b95bb0cab495f48","name":"","spec":"rfc","sep":",","hdrin":true,"hdrout":"all","multi":"mult","ret":"\\n","temp":"","skip":"0","strings":true,"include_empty_strings":false,"include_null_values":false,"x":170,"y":1220,"wires":[["30015a5bc76a1908"]]},{"id":"3175b64c8926a811","type":"template","z":"1b95bb0cab495f48","name":"Valid CSV (LF in col c and in row 3)","field":"payload","fieldType":"msg","format":"handlebars","syntax":"mustache","template":"a'a,\"b,b\",\"c\"\"\nc\",d.d\na,b,c,\n,2,3,4\ni,j,l,\"m\nm\"\n","output":"str","x":260,"y":1160,"wires":[["fd20062fe2b65617"]]},{"id":"c7e4ced886d5fa0c","type":"subflow:fb90d993b5466b3c","z":"1b95bb0cab495f48","name":"JSON array of objects","env":[{"name":"test","value":"deepStrictEqual","type":"str"},{"name":"expected","value":"[{\"a'a\":\"a\",\"b,b\":\"b\",\"c\\\"\\nc\":\"c\"},{\"b,b\":2,\"c\\\"\\nc\":3,\"d.d\":4},{\"a'a\":\"i\",\"b,b\":\"j\",\"c\\\"\\nc\":\"l\",\"d.d\":\"m\\nm\"}]","type":"json"},{"name":"Expected","value":"a'a,\"b,b\",\"c\"\"c\",d.d,e`e\\n1,2,3,4,5\\n5,4,3,2,1\\n","type":"str"}],"x":340,"y":640,"wires":[["5becc370e0370a82"]]},{"id":"5becc370e0370a82","type":"debug","z":"1b95bb0cab495f48","name":"Legacy mode","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":360,"y":700,"wires":[]},{"id":"30015a5bc76a1908","type":"subflow:fb90d993b5466b3c","z":"1b95bb0cab495f48","name":"JSON array of objects","env":[{"name":"test","value":"deepStrictEqual","type":"str"},{"name":"expected","value":"[{\"a'a\":\"a\",\"b,b\":\"b\",\"c\\\"\\nc\":\"c\"},{\"b,b\":2,\"c\\\"\\nc\":3,\"d.d\":4},{\"a'a\":\"i\",\"b,b\":\"j\",\"c\\\"\\nc\":\"l\",\"d.d\":\"m\\nm\"}]","type":"json"},{"name":"Expected","value":"a'a,\"b,b\",\"c\"\"c\",d.d,e`e\\n1,2,3,4,5\\n5,4,3,2,1\\n","type":"str"}],"x":340,"y":1220,"wires":[["f67363a8f7563c55"]]},{"id":"f67363a8f7563c55","type":"debug","z":"1b95bb0cab495f48","name":"RFC Mode","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":370,"y":1280,"wires":[]}]
```

#### Example: where CSV node fails to correctly stringify to RFC compliant output
image

```json
[{"id":"fb90d993b5466b3c","type":"subflow","name":"Expect","info":"","category":"function","in":[{"x":80,"y":160,"wires":[{"id":"b7d75d6fb82e713b"}]}],"out":[{"x":450,"y":160,"wires":[{"id":"b7d75d6fb82e713b","port":0}]}],"env":[{"name":"property","type":"str","value":"payload","ui":{"icon":"font-awesome/fa-ellipsis-v","label":{"en-US":"Property"},"type":"input","opts":{"types":["str"]}}},{"name":"test","type":"str","value":"strictEqual","ui":{"icon":"font-awesome/fa-exclamation","label":{"en-US":"Test"},"type":"select","opts":{"opts":[{"l":{"en-US":"strictEqual"},"v":"strictEqual"},{"l":{"en-US":"deepStrictEqual"},"v":"deepStrictEqual"},{"l":{"en-US":"match"},"v":"match"},{"l":{"en-US":"notStrictEqual"},"v":"notStrictEqual"},{"l":{"en-US":"notDeepStrictEqual"},"v":"notDeepStrictEqual"},{"l":{"en-US":"doesNotMatch"},"v":"doesNotMatch"}]}}},{"name":"expected","type":"str","value":"","ui":{"icon":"font-awesome/fa-question-circle-o","label":{"en-US":"Expect"}}},{"name":"mode","type":"str","value":"throw","ui":{"icon":"font-awesome/fa-check-square","label":{"en-US":"Mode"},"type":"select","opts":{"opts":[{"l":{"en-US":"Throw on fail"},"v":"throw"},{"l":{"en-US":"Warn only"},"v":"dont-throw"}]}}}],"meta":{"module":"test-expected-payload","type":"test-expected-payload","version":"1.0.0","author":"Steve-Mcl","desc":"Test msg.expected vs msg.payload","keywords":"test,expected"},"color":"#C7E9C0","outputLabels":["msg"],"icon":"font-awesome/fa-file-code-o","status":{"x":420,"y":280,"wires":[{"id":"0082523530ce9a0d","port":0}]}},{"id":"b7d75d6fb82e713b","type":"function","z":"fb90d993b5466b3c","name":"test","func":"// let payload = cleanString(msg.payload)\n// let expected = cleanString(msg.expected || env.get('expected'))\nnode.status({fill:\"yellow\",shape:\"ring\",text:prefixTimeString(\"testing...\")});\n\nfunction prefixTimeString(str) {\n    const n = new Date();\n    const hours = String(n.getHours()).padStart(2, '0');\n    const minutes = String(n.getMinutes()).padStart(2, '0');\n    const seconds = String(n.getSeconds()).padStart(2, '0');\n    return `${hours}:${minutes}:${seconds}: ${str}`;\n}\n\nfunction cleanString(str) {\n    if (typeof str === \"object\") {\n        str = JSON.stringify(str)\n    }\n    if (typeof str !== \"string\") {\n        str = RED.util.ensureString(str)\n    }\n  const replacedString = str.replace(/\\r/g, \"\\\\r\").replace(/\\n/g, \"\\\\n\");\n  return replacedString;\n}\nconst dontThrow = env.get('mode') === 'dont-throw' // default is 'throw'\nconst prop = env.get(\"property\") || 'payload'\nlet payload = RED.util.getMessageProperty(msg,prop);\nif (typeof payload === 'string') {\n    payload = cleanString(payload)\n}\nlet expected = msg.expected || env.get('expected')\nif (typeof expected === 'string') {\n    expected = cleanString(expected)\n}\n\ntry {\n    const assersion = env.get(\"test\");\n    const test = assert[assersion]\n    if (!assersion || typeof test !== \"function\") {\n        throw new Error(`'${assersion}' is not a valid assertion`)\n    }\n\n    // node.warn({\n    //     assersion,\n    //     payload,\n    //     expected,\n    //     test\n    // })\n    test(payload, expected)\n\n    setTimeout(function() {\n        node.status({fill:\"green\",shape:\"ring\",text:prefixTimeString(\"pass\")});\n        node.send(msg)\n    }, 125);\n} catch (error) {\n    setTimeout(function() {\n        node.status({fill:\"red\",shape:\"dot\",text:prefixTimeString(\"fail\")});\n        const m2 = RED.util.cloneMessage(msg);\n        m2.expectedString = cleanString(expected)\n        m2.payloadString = cleanString(payload)\n        if (dontThrow) {\n            node.warn(error);\n            node.send(msg)\n        } else {\n            node.error(error, msg);\n            // throw error\n        }\n    }, 125);\n};\n","outputs":1,"timeout":0,"noerr":0,"initialize":"","finalize":"","libs":[{"var":"assert","module":"assert"}],"x":250,"y":160,"wires":[[]]},{"id":"0082523530ce9a0d","type":"status","z":"fb90d993b5466b3c","name":"","scope":["b7d75d6fb82e713b"],"x":270,"y":280,"wires":[[]]},{"id":"e9f904422f90063c","type":"inject","z":"1b95bb0cab495f48","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[{\"c\\\"c\":3,\"d.d\":4,\"b,b\":2,\"e`e\":5,\"a'a\":1},{\"d.d\":2,\"e`e\":1,\"b,b\":4,\"c\\\"c\":3,\"a'a\":5}]","payloadType":"json","x":75,"y":100,"wires":[["6ce0c4db043c79ee"]],"l":false},{"id":"6ce0c4db043c79ee","type":"csv","z":"1b95bb0cab495f48","name":"a'a,\"b,b\",\"c\"\"c\",d.d,e`e","spec":"","sep":",","hdrin":"","hdrout":"all","multi":"one","ret":"\\n","temp":"a'a,\"b,b\",\"c\"\"c\",d.d,e`e","skip":"0","strings":true,"include_empty_strings":"","include_null_values":"","x":240,"y":100,"wires":[["9d5f7a4f472eb8d1"]]},{"id":"5ba5475eeb800bbb","type":"comment","z":"1b95bb0cab495f48","name":"RFC Valid template with embeded quotes (Legacy Mode)","info":"#### Demo 5\n\nColumn Template\n```\na'a,\"b,b\",\"c\"\"c\",d.d,e`e\n```\n\nparses as\n```\n['a'a', 'b,b', 'cc', 'd.d', 'e`e']\n//a'a   \"b,b\"   cc    d.d    e`e\n```\n\nAccording to RFC4180 2.7 this should be\n```\n[ \"a'a\", 'b,b', 'c\"c', 'd.d', 'e`e' ]\n// a'a    b,b    c\"c    d.d    e`e    just values\n// a'a,\"b,b\",\"c\"\"c\",d.d,e`e           as a CSV string\n```\n\n\n--- \n\nUsing https://www.npmjs.com/package/@vanillaes/csv\n\n```\ncsv.parse('a\\'a,\"b,b\",\"c\"\"c\",d.d,e`e')\n// [ [ \"a'a\", 'b,b', 'c\"c', 'd.d', 'e`e' ] ]\n```","x":250,"y":60,"wires":[]},{"id":"3cf28122dbdd742a","type":"inject","z":"1b95bb0cab495f48","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[{\"c\\\"c\":3,\"d.d\":4,\"b,b\":2,\"e`e\":5,\"a'a\":1},{\"d.d\":2,\"e`e\":1,\"b,b\":4,\"c\\\"c\":3,\"a'a\":5}]","payloadType":"json","x":75,"y":340,"wires":[["ed7df3d3487db154"]],"l":false},{"id":"9d5f7a4f472eb8d1","type":"subflow:fb90d993b5466b3c","z":"1b95bb0cab495f48","name":"a'a,\"b,b\",\"c\"\"c\",d.d,e`e\\n1,2,3,4,5\\n5,4,3,2,1\\n","env":[{"name":"expected","value":"a'a,\"b,b\",\"c\"\"c\",d.d,e`e\\n1,2,3,4,5\\n5,4,3,2,1\\n","type":"str"},{"name":"mode","value":"dont-throw","type":"str"},{"name":"Expected","value":"a'a,\"b,b\",\"c\"\"c\",d.d,e`e\\n1,2,3,4,5\\n5,4,3,2,1\\n","type":"str"}],"x":270,"y":160,"wires":[["48290d8baa5f8899"]]},{"id":"ed7df3d3487db154","type":"csv","z":"1b95bb0cab495f48","name":"a'a,\"b,b\",\"c\"\"c\",d.d,e`e","spec":"rfc","sep":",","hdrin":"","hdrout":"all","multi":"one","ret":"\\n","temp":"a'a,\"b,b\",\"c\"\"c\",d.d,e`e","skip":"0","strings":true,"include_empty_strings":"","include_null_values":"","x":240,"y":340,"wires":[["f47714744cbeeb10"]]},{"id":"48290d8baa5f8899","type":"debug","z":"1b95bb0cab495f48","name":"Legacy mode","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":360,"y":220,"wires":[]},{"id":"80045c1aeb0bdcd5","type":"debug","z":"1b95bb0cab495f48","name":"RFC Mode","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":370,"y":460,"wires":[]},{"id":"0dde071c77c651b0","type":"comment","z":"1b95bb0cab495f48","name":"RFC Valid template with embeded quotes (RFC Mode)","info":"#### Demo 5\n\nColumn Template\n```\na'a,\"b,b\",\"c\"\"c\",d.d,e`e\n```\n\nparses as\n```\n['a'a', 'b,b', 'cc', 'd.d', 'e`e']\n//a'a   \"b,b\"   cc    d.d    e`e\n```\n\nAccording to RFC4180 2.7 this should be\n```\n[ \"a'a\", 'b,b', 'c\"c', 'd.d', 'e`e' ]\n// a'a    b,b    c\"c    d.d    e`e    just values\n// a'a,\"b,b\",\"c\"\"c\",d.d,e`e           as a CSV string\n```\n\n\n--- \n\nUsing https://www.npmjs.com/package/@vanillaes/csv\n\n```\ncsv.parse('a\\'a,\"b,b\",\"c\"\"c\",d.d,e`e')\n// [ [ \"a'a\", 'b,b', 'c\"c', 'd.d', 'e`e' ] ]\n```","x":240,"y":300,"wires":[]},{"id":"f47714744cbeeb10","type":"subflow:fb90d993b5466b3c","z":"1b95bb0cab495f48","name":"a'a,\"b,b\",\"c\"\"c\",d.d,e`e\\n1,2,3,4,5\\n5,4,3,2,1\\n","env":[{"name":"expected","value":"a'a,\"b,b\",\"c\"\"c\",d.d,e`e\\n1,2,3,4,5\\n5,4,3,2,1\\n","type":"str"},{"name":"mode","value":"dont-throw","type":"str"},{"name":"Expected","value":"a'a,\"b,b\",\"c\"\"c\",d.d,e`e\\n1,2,3,4,5\\n5,4,3,2,1\\n","type":"str"}],"x":270,"y":400,"wires":[["80045c1aeb0bdcd5"]]}]
```

### Implementation and key differences between Legacy and RFC mode
Following discussions with @dceejay we came to agreement on the following features:
1. Introduces RFC mode via a "Specification" option that permits the user to select between "Legacy" mode or use the new parser in "RFC Mode"
   * Any existing flow would continue to use Legacy Mode
   * Opening a CSV node, then clicking Done should NOT mark it as dirty
   * A form-tip would be added beneath the "Specification" option stating that "Legacy mode will be removed in the future"
   * Under the hood:
     * The whole original legacy parsing code is kept, virtually untouched, wrapped in a simple `if(legacyMode) {...}` block. This makes it much easier to separate functionality and avoid lots of hot path if(legacy)-else(rfc) switching.
     * The new RFC parser is a implemented in a separate lib (see "Why move CSV parsing to a separate lib" below for more info)
2. In RFC Mode, the Column Template will **always** be parsed in strict mode (e.g. quotes should be escaped, spaces are respected etc)
3. In addition to the existing one time debug warning declaring the "malformed template", `node.status` is added as a permanent visual cue that the node is misconfigured
4. We won't enforce the RFC spec with regards to line separators (RFC Section 2.1 states "Each record is located on a separate line, delimited by a line break (CRLF)") however, see next point
5. Related to the previous point, any new CSV node added to the canvas will be set for RFC mode by default including setting the line separators to `\r\n` (as per RFC 2.1) 
   * existing flows will continue to use the line separator originally set by the user
   * the option to select non standard line separators `\n` and `\r` is still possible in RFC mode
6. Bad input data (e.g. boolean, single number) will be handled differently in RFC mode
   * instead of passing the bad data through, the node will throw a catchable error and set its status to indicate the error
   * this fact is also highlighted in the built in help text
   * for reference, in legacy mode, only a non catchable warning is sent to the debug sidebar, no status is set and the bad data is passed through without anything in the msg to indicate it is bad/unprocessed. This meant the user/flow had easy means to determine if the parse worked correctly or not (albeit the user could store the input and test against the output of the CSV node to determine if it was converted from string to _something_ or  _something_ to string)
7. When parsing numeric values, the newer RFC mode will also parse binary, octal and hexadecimal value notation strings

_NOTE: https://onlinecsvtools.com/convert-csv-to-json does a good job of RFC compliant conversions and was often used to cross check this dev_

### Why move CSV parsing to a separate lib?

There were 3 primary reasons for pulling the CSV parsing out to a lib:
1. To simplify implementation while keeping Legacy Mode
2. For future (standalone) unit tests on the lib as its own thing
3. A possibility to add a new mode to the template node.  Currently there is "Parse Json" and "Parse Yml" options. 
   It would not be unreasonable to see a future where we permit the template node to offer "Parse CSV"

### Tests

All of the original legacy tests were kept for legacy mode. Where necessary,
`try...catch` was added to improve test fail feedback _(tests in with `done` callbacks timeout instead of failing with a specific reason, making it difficult to determine why a test fails)

All of the original legacy tests were duplicated for RFC mode and where necessary, fixed up to suit RFC mode.  Those are detailed below.

#### Differences between Legacy and RFC mode _as highlighted by the tests_:
TEST: "should be loaded with defaults"
* In RFC mode, the line separator is set to `\r\n` as per RFC4180 Section 2.1
* In Legacy mode, the line separator is set to `\n`

TEST: "should convert a simple string to a javascript object with space separator (with spaced template)"
* In RFC mode, spaces are respected in the template (RFC4180 Section 2.4)
* In legacy mode, the template is "A, B, , D" is trimmed to "A,B,D"

TEST: "should not remove quotes and whitespace from template"
* In RFC mode, the column template is parsed in strict mode
* meaning this template is invalid because:
   * it encounters a quote in an unquoted field (the "b" in the 2nd column)
      * The 2nd column starts with a space but then a single quote is encountered. RFC4180 Section 2.6 
        says Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes
   * it contains a data between the closing quote and separator (4th column starts ok but then has a space after the closing quote)
      * Since we adhere to RFC4180 Section 2.4, "Spaces are considered part of a field and should not be ignored"
        we must treat the space as part of the data meaning field is not correctly close with a quote

TESTS: 
"should allow commas and spaces in the template"
"should allow passing in a template as first line of CSV"
"should allow passing in a template as first line of CSV (not comma)"
"should allow passing in a template as first line of CSV (special char /)"
"should allow passing in a template as first line of CSV (special char \\)"

* In RFC mode, spaces are respected in the template (RFC4180 Section 2.4)
* In legacy mode, the template `a,b b,\"c,c\",\" d, d \"` is trimmed to `a,b b,"c,c","d, d"`

TEST: "should convert a simple object back to a csv"
* By default, the legacy mode parser will use `\n` as the line separator
* The RFC mode parser will use `\r\n` as the line separator as per RFC4180 Section 2.1
* This is configurable in both modes meaning that the legacy mode parser can be made to use `\r\n` and the RFC mode parser can be made to use `\n`
* Any existing flows will still use the line ending that they were created with as it will be stored in the flow file

TEST: "should convert a simple object back to a csv with no template"
* line separator handling:
*   By default, the legacy mode parser will use `\n` as the line separator
*   The RFC mode parser will will use `\r\n` as the line separator as per RFC4180 Section 2.1 spaces:
*   By default, the legacy mode parser will trim spaces from the start and end template columns
*   The RFC mode parser will not trim spaces from the start and end template columns (RFC4180 Section 2.4)
*   This means the original test flow, when ran in RFC mode, was expecting to find a prop name of " " in the input data object
* To make this test work, we need to change the template to not be a space!

TEST: "should not call done or pass the bad msg through when input causes an error - should throw error and set status"
* In RFC mode, instead of passing the bad data through, the node will throw an error and set the status to indicate the error
* in legacy mode, the bad data is passed through and a none catchable warning is sent to the debug sidebar

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `npm run test` to verify the unit tests pass
- [x] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by dceejay** [comment]
Hi - sorry taken a while - quick first look... When I switch to legacy I see
image
(I did a git build after pulling the PR so I should have all the files ? or am I messing something where the yellow bar is ?)
Also can we tweak the width of the left margin so the " icon Specification" fits on one line.

**Comment by dceejay** [comment]
But yes - apart from nits -- functionality good with me !

**Comment by Steve-Mcl** [comment]
> Hi - sorry taken a while - quick first look... When I switch to legacy I see image (I did a git build after pulling the PR so I should have all the files ? or am I messing something where the yellow bar is ?) 

Will have a look at my local dev see if there is a missed commit. 


Also can we tweak the width of the left margin so the " icon Specification" fits on one line.

Must be a browser or font thing. Will tell layout.

**Comment by Steve-Mcl** [comment]
@dceejay I fixed the layout by changing the property label to **Parser** (rather than messing with styles/csv)

corrected the i18n tip message too

chrome_Ii7oiA7eKo

**Comment by dceejay** [comment]
Yes - all good with me now... roll on v4 !

**Pull request merged**
