### PR TITLE
Added split node to split message into array or series of messages

### PR DESCRIPTION
**Pull request by annaet**
Created the pull request for this just so we remember to do something with it :) 

It uses the same code from the CSV node for its seperators with the addition of a new line seperator and if the incoming message is an array it will split that into a series of messages.

### CODE REVIEW

**Comment by elidoran** [comment]
This PR has been hanging out for nearly a year. Want to do something else with it before committing? Or, close it instead?

**Comment by knolleary** [comment]
@elidoran I've left it hanging around as we do want a node like this at some point, but it needs some wider consideration as implied by @Belphemur comment. But it simply hasn't bubbled up the priority list to get done.

**Comment by elidoran** [comment]
What can I do to help you along?

**Comment by knolleary** [comment]
Closing as we have the new split/join node pair coming in 0.14

**Pull request closed without merging**
