### PR TITLE
Fix `this` context when calling multiple event listeners (fixes #2692).

### LINKED ISSUE #2692: `this` context is different between single and multiple input listeners
The Node class handles certain events by its own. It does this by intercepting some EventEmitter methods like `on` and `emit`. There is a difference in how the callback is called when you multiple event listeners registered.

The "single event listener" code path calls the callback as a "method" which means that the `this` context is the object that you call the "method" on: https://github.com/node-red/node-red/blob/80d100f3f9cc41ed4489ee33424b7c6560d9c4f5/packages/node_modules/%40node-red/runtime/lib/nodes/Node.js#L200-L204

The "multiple event listeners" code path calls the callbacks on an array element which causes the `this` context to become the array itself: https://github.com/node-red/node-red/blob/80d100f3f9cc41ed4489ee33424b7c6560d9c4f5/packages/node_modules/%40node-red/runtime/lib/nodes/Node.js#L217-L226

Node.js REPL demo:
```js
Welcome to Node.js v12.18.0.
Type ".help" for more information.
> {inputCallbacks:[function(){console.log(this);}]}.inputCallbacks[0]()
[ [Function] ]
undefined
> {inputCallback:function(){console.log(this);}}.inputCallback()
{ inputCallback: [Function: inputCallback] }
undefined
>
```

### What are the steps to reproduce?

Add two or more `input` event listeners on to a node.

### What happens?

The `this` context of the callback is the array of event listener callbacks (the `_inputCallbacks` property)

### What do you expect to happen?

The `this` context is the same as if there is only one `input` event listener which is the node instance itself.

### Please tell us about your environment:

- [x] Node-RED version: Git: 80d100f3f9cc41ed4489ee33424b7c6560d9c4f5
- [x] Node.js version: 12.18.0
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

### PR DESCRIPTION
**Pull request by mgroenhoff**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

Fixes #2692

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [x] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by knolleary** [comment]
Looks good - thanks for this.

**Comment by mgroenhoff** [comment]
Wow, that was quick! I noticed a typo in the test which I pushed but it's closed already.

**Comment by knolleary** [comment]
Oops. I got a bit merge happy as it looked good. What's the fix on the test?

**Comment by mgroenhoff** [comment]
It was a missing `msg` argument in the second event listener. I have corrected it in my form. You can diff it to see the change.

**Comment by knolleary** [comment]
Got it - thanks

**Pull request merged**
