### PR TITLE
Exec: Preserve existing properties on msg object

### PR DESCRIPTION
**Pull request by akashmugu**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

[Exec Node] has three outputs (stdout, stderr and return code)

According to the [documentation](https://nodered.org/docs/creating-nodes/node-js#sending-messages), if a node has an input, it should preserve the existing properties on the message for the rest of the flow. This rule is obeyed by 2 inputs (stdout and stderr) but not by the third (return code)

After this fix, all the 3 outputs of [Exec Node] will start preserving the existing properties on the msg object

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [x] I have added suitable unit tests to cover the new/changed functionality

[Exec Node]: https://github.com/node-red/node-red/blob/master/nodes/core/core/75-exec.js

### CODE REVIEW

**Comment by knolleary** [comment]
Hi - thanks for this.

It would be great to have the unit test updated to cover this - https://github.com/node-red/node-red/blob/master/test/nodes/core/core/75-exec_spec.js

Let me know if that's something you're able to do.

**Comment by akashmugu** [comment]
I added unit tests to cover this fix. I searched for similar unit tests(which check if the existing properties of msg object are preserved or not) of other nodes for reference with no success. As it is a [suggestion](https://nodered.org/docs/creating-nodes/node-js#sending-messages) and not a feature, it can be easily missed in tests

@knolleary Do you think it makes sense to have a generic(in unit test of any node) warning at [node-red-node-test-helper](https://www.npmjs.com/package/node-red-node-test-helper) level in the following way:
* Inject a random property to the [receive](https://www.npmjs.com/package/node-red-node-test-helper#receiving-messages-from-nodes) end of the node
* Check if that property exists on inputs of all the wires of the node
* If not, notify the developer that this particular node is not preserving the existing properties of msg object

**Comment by knolleary** [comment]
@akashmugu there are valid reasons not to pass on the properties which cannot be codified in any automated test. It's up to the node author to do the right thing.

**Comment by knolleary** [comment]
This has been manually merged to the `dev` branch as it is new funciton. Thanks!

**Pull request closed without merging**
