### PR TITLE
Show port label of subflow with input port

### PR DESCRIPTION
**Pull request by Kazuki-Nakanishi**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

subflow edit dialog does not show an input port label correctly.  The reproduction procedure is as follows.

1. Create a subflow.
2. Change the number of input port from 0 to 1.
3. Click `edit properties`, and open `Appearance` tab.

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by knolleary** [comment]
Thanks @Kazuki-Nakanishi 

I can confirm the original issue, but testing this PR doesn't appear to fix it for me. I don't see the label fields change at all, no matter what adding or removing of inputs *or* outputs I do.

**Comment by Kazuki-Nakanishi** [comment]
Hmm, I checked that this PR works on Windows and Linux (I have no mac right now).
Could you tell me the value of both `childCount` and `inputCount` at line 579 of editor.js when you opened `Appearance` tab?  In my case, `childCount` is 1 and `inputCount` is 0.

**Comment by knolleary** [comment]
There is some further special handling needed. The initial count of inputs/outputs comes from `node.in.length` and `node.out.length` for subflows. This is handled properly when building the initial form, but the refresh function doesn't take it into account. The fix in this PR is needed, so I'll merge - and will follow up with the additional fix needed.

**Comment by Kazuki-Nakanishi** [comment]
Thank you very much for fixing and explaining it.  I understand it.

**Pull request merged**
