### PR TITLE
Add description to flow same as subflow

### PR DESCRIPTION
**Pull request by Kazuki-Nakanishi**
This is the PR for #1194
I finally chose "2" because the output is similar to subflow.
If look and feel is weird, please let me know.
(sorry, I closed the previous PR, and sent this again.)

### CODE REVIEW

**Comment by knolleary** [comment]
Hi @Kazuki-Nakanishi, thanks for this.

We were thinking whether we wanted to add an `info` field to all nodes, as a standard property allowing any node to have additional information added. Want to make sure that any change made here would be compatible with such a future change. Will think about it and aim to finalise next week before we merge this PR.

Thanks.

**Comment by Kazuki-Nakanishi** [comment]
Hi @knolleary,

Thank you for your consideration.
Adding an info field to all nodes would be nice although we need to carefully realize it from the UI point of view.

Adding a row of info field to node properties is a simple idea, but I come up with three items that need to be considered.
1. The size of description field becomes smaller than the one of current description field for subflow.
2. Node user's description comes before node developer's description (not sure it is good or not).
3. The number of input items increases by one.

I think that the third item is the most important thing.
Adding an input item to tab or subflow is OK because of the following reasons.
* They always have only a few input items.
* Adding description to each tab or subflow is a good thing and it should be encouraged.

Adding an input item to nodes may be not OK because of the following reasons.
* They sometimes already have many input items.
* Node user may not use info property (and in that case, info field becomes an obstacle for the user).

For the above reason, I feel that using system-wide node properties (https://trello.com/c/8gjbzRKn/67-system-wide-node-properties) is one of good ways because an info field does not appear when user double-clicks a node.

Thanks,

**Comment by UHaessler** [comment]
[User Settings Dialog](https://trello.com/c/3IN3Vppv/85-user-settings-dialog)

**Comment by knolleary** [comment]
Hi,

yes, when I talk about adding an info property to all nodes it would be showing in the edit dialog as a collapsible section similar to the `port labels` we've added in 0.17.

Have been tied up with lots of other things the last couple of weeks - hope to make progress on this general area very soon.

**Comment by Kazuki-Nakanishi** [comment]
Hi,

Thank you for your reply.  Please work on it when you are convenient.
And if I can help something, please let me know.

Thanks,

**Pull request merged**
