### PR TITLE
Extend exec node

### PR DESCRIPTION
**Pull request by chatper**
You can set the command from msg via the msg.cmd property

### CODE REVIEW

**Comment by dceejay** [comment]
why do we need this ? you can set the configured command to blank, and then inject the complete command as `msg.payload`.

**Comment by chatper** [comment]
It was not clear to me that you can do that. As a matter of fact I still cannot get it to work like that. I'm using this simple flow:
`[{"id":"716c755.1ce9f8c","type":"exec","z":"5b98848c.26103c","command":"","addpay":true,"append":"","useSpawn":"","timer":"","name":"","x":450,"y":240,"wires":[["84fe3ba2.71fe48"],[],[]]}]`

**Comment by dceejay** [comment]
how about this...

[{"id":"f948aad5.b71fb8","type":"inject","z":"2df73bf4.4747c4","name":"","topic":"","payload":"ls *.json","payloadType":"str","repeat":"","crontab":"","once":false,"x":110,"y":980,"wires":[["584995d7.437e0c"]]},{"id":"584995d7.437e0c","type":"exec","z":"2df73bf4.4747c4","command":" ","addpay":true,"append":"","useSpawn":"","timer":"","name":"","x":290,"y":1000,"wires":[["71332775.cb50d8"],[],[]]},{"id":"71332775.cb50d8","type":"debug","z":"2df73bf4.4747c4","name":"","active":true,"console":"false","complete":"false","x":463,"y":975,"wires":[]}]

**Comment by chatper** [comment]
I get an empty string whatever command I use. I'm using Node-RED version: v0.16.2-git.

**Comment by dceejay** [comment]
well you need to make the command something that will work for you... I had `ls *.json` - so unless you have any json files you won't get anything :-)

**Comment by chatper** [comment]
yeah I know,  that's why I said "whatever command I use" :) . I already tried a couple of more generic  commands like `pwd` and `ls`. I always get an empty string, which should not be the case.

**Comment by dceejay** [comment]
which version of node.js ?

**Comment by chatper** [comment]
v7.7.3

**Comment by dceejay** [comment]
in your `settings.js` file can you add a line
    verbose:true,
and restart... - It should then print out the command line it thinks it is executing...

**Comment by chatper** [comment]
I used `node red.js -v` which is the same thing and the output I get is `[exec:3b1e4a67.483e0e] undefined ls`. Is it actually working for you?  Isn't setting the command property on node configuration required? (I edited this section `command: {value:"",required:true},` in this [file](https://github.com/node-red/node-red/blob/master/nodes/core/core/75-exec.html) and that's why I can mess with this, but is this the case for you as well?)

**Comment by dceejay** [comment]
yes - working for me on node v6.10.1... 
yes - I set it to " " in my flow I pasted above.

**Comment by dceejay** [comment]
any progress ?

**Comment by sbarwe** [comment]
@dceejay your flow is working for me on win10 and linux node 6.9.5 setting command to " ". 
Setting to undefined does not work for me, as command is required - I will get a "node is not configured" notification. 
The only difference is that on windows I get a "Buffer" in the debug pane and on linux a "String-Array" as the payload result. But content itself are both correct

**Comment by dceejay** [comment]
interesting (re win vs linux)... is that always the case ? what command did you run (ie did you expect to get a buffer back ?, and indeed what was the result ? was it an empty string ?) it does try to detect if it's utf8  and if so converts to a string... which should work across platforms... but...

**Comment by sbarwe** [comment]
it was "dir *.js" vs "ls *.js" 
Linux cmd-line: NODE_ENV="development" node --debug /usr/bin/node-red -v -s /home/pi/.node-red/settings_empty.js --title "NR Empty" | ccze -A

Win cmd-line: cross-env NODE_ENV=development node red.js -v

on linux NR 0.16.2 (official release) on win 0,17 branch from git

Result was in both cases a correct directory listing (on win I needed to convert to "raw string" in the debug pane, as it was a buffer - indeed exptected strings as on linux)

**Comment by chatper** [comment]
I reinstalled node-red, this time using npm (previously I followed [this](https://github.com/node-red/node-red#developers) guide and finally got the expected results.

**Comment by dceejay** [comment]
OK - going to close this PR. (but will think about removing the required:true from the command window)

**Pull request closed without merging**
