### PR TITLE
Use new Orion editor for function, template and comments nodes.

### PR DESCRIPTION
**Pull request by libingw**
This is a pull request for using the new Orion stand alone editor with the full set of language tooling. The Orion editor build is not included in the pull request. You need to download the build from https://www.eclipse.org/downloads/download.php?file=/orion/drops/I20150610-2236/built-codeEdit.zip and unzip it into "Node Red Code Base\editor\vendor\orion" folder.

Please note the Orion build mentioned in the link is a tested nightly build.

### CODE REVIEW

**Comment by dceejay** [comment]
the build is gone already... - will any of the 9.0 Stream integration Builds - built-codeEdit be OK ?
(Obviously we can't take this PR without a stable build but ... presumably that will happen at some point ?)

**Comment by libingw** [comment]
Thanks Dave. Sorry I did not realize that our download page only hosts the last 3 days nightly build. We will release Orion 9.0 on June 24th. We will have a stable branch tonight (June 15th) and build it as Orion Editor 9.0 candidate. Once the stable build is up I will do a smoke test and let you know. You can give it a try and if there is anything wrong we can try to fix it before 9.0 goes out.

**Comment by libingw** [comment]
Hi Dave, could you please try this stable build? https://www.eclipse.org/downloads/download.php?file=/orion/drops/S20150616-1107/built-codeEdit.zip.
I've downloaded this build and applied to my local node red dev environment. Everything works fine except some tooltip positioning issues that we are fixing right now and will be addressed in the 9.0 release. But please try this build now and your feed back is much appreciated.

**Comment by knolleary** [comment]
Closing as this is all fairly out of date now.

**Pull request closed without merging**
