### PR TITLE
chore: migrate api `node-sass` to `dart-sass`

### PR DESCRIPTION
**Pull request by Rotzbua**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

Migrate from legacy api (`node-sass`) to new api (`dart-sass`).
https://sass-lang.com/documentation/js-api/#md:legacy-api

Effectively only replaces the function call.

## Reference

#4723

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `npm run test` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by bonanitech** [comment]
#3743 does that (and some other stuff). Should I close it in favor of this one?

**Comment by knolleary** [comment]
@bonanitech as you're probably the main user of the script, I'd value your input on which PR we should proceed with. We don't need both, but if you feel your PR addresses more items you'd like to see addressed, then we can go with that.

**Comment by bonanitech** [comment]
Thank you @knolleary

To be honest I don't use it anymore. I have one in the theme-collection repository.

But I think #3743 can benefit other people trying to create themes. With the changes made in that PR, the script will generate a file in the format Node-RED uses nowadays, containing only the CSS variables.

**Comment by knolleary** [comment]
Thanks @bonanitech - we'll close this one in favour of your other PR.

**Pull request closed without merging**
