### PR TITLE
Update Monaco to V0.33.0

### PR DESCRIPTION
**Pull request by Steve-Mcl**
## Proposed changes
Update monaco to from 0.28.1 to latest version (0.33.0) (built in this PR: [node-red/nr-monaco-build #2](https://github.com/node-red/nr-monaco-build/pull/2))

The changes in this are mostly to get past under the hood changes in monaco between 0.28.1 ~ 0.30.0 that caused the [monaco build project](https://github.com/node-red/nr-monaco-build) to fail.  This now lets us do future monaco upgrades once more (unless the monaco changes things again) - that said, 0.33.0 does have a number of improvements and bug fixes (under the hood, just not immediately noticeable to user).

This update also includes all the improvements made by updating deps in node-red/nr-monaco-build to latests versions including Monaco Themes updates in 0.4.1. 

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] I have run `grunt` to verify the unit tests pass

### CODE REVIEW

**Review by knolleary — APPROVED** [review]

**Comment by knolleary** [comment]
One additional task - we should make sure we create a release in the https://github.com/node-red/nr-monaco-build/releases repo to capture the exact set of files that are being added here.

**Comment by Steve-Mcl** [comment]
> One additional task - we should make sure we create a release in the https://github.com/node-red/nr-monaco-build/releases repo to capture the exact set of files that are being added here.

Do you mean publish a dist or simply tag the release?
could you show me please?

**Comment by Steve-Mcl** [comment]
@knolleary 

Done https://github.com/node-red/nr-monaco-build/releases/tag/0.33.0 👍

**Comment by Steve-Mcl** [comment]
@knolleary unwanted theme removed.  Ready for review / merge upon your approval.

**Pull request merged**
