### PR TITLE
Update Chinese message for debug node

### PR DESCRIPTION
**Pull request by JiyeYu**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by JiyeYu** [comment]
@kazuhitoyokoi I updated it

**Comment by kazuhitoyokoi** [comment]
@JiyeYu Thanks a lot!

**Comment by JiyeYu** [comment]
@kazuhitoyokoi Travis failed the last two jobs. Can you help me rerun it? Thank you

**Comment by kazuhitoyokoi** [comment]
@JiyeYu I executed Travis testing again. :)

**Pull request merged**
