### PR TITLE
Monaco (rebuilt)

### PR DESCRIPTION
**Pull request by Steve-Mcl**
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes
Introduce monaco editor to node-red
See discussion [on the node-red forum](https://discourse.nodered.org/t/using-monaco-editor-monaco-branch-now-in-fork/26561)

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### Editor Packaging...
~~My early attempts to add monaco using AMD caused lots of errors like "Uncaught Error: Can only have one anonymous define call per script file"~~
~~I spent a lot of time on this but ultimately without modifying how node-red is built, I could not work around it.~~
~~I ended up generating a build using parcel.~~

Monaco is now built using webpack - this tidies up the hashed files and has helped me get monaco locales working.
See readme in src

### themes...
By default, monaco has 3 built in themes "vs" "vs-dark" and "hc-black"
Also, a collection of themes for monaco were added. The user can chose a default theme by specifying it in 
`editorTheme.codeEditor.options.theme` (see example settings.js below)
If omitted, the theme "vs" is used

### mobile...
I have not tested IOS but others have (discussed in the main thread)
On Android, I had to change keyboard to a programmers keyboard (worked great with "Codeboard Keyboard for coding")

### fall-back / safety
As discussed, monaco is loaded as an asset (vendorMonaco) in index.mst. 
In short, if monaco is not the selected editor (`editorTheme.codeEditor.lib`), it is not loaded (will not be bootstrapped) and node-red falls back to ACE 

#### Internet explorer...
If internet explorer is detected and monaco is the selected editor, it will fall back to ACE

### Supported languages...
Monaco comes bundled with about 66 programming languages from to APEX to YAML. 
Some size reduction could be achieved by removing these however only about 369KB - but- as contrib nodes like INI file and UIBUILDER exist, I would hope we would leave all language files included to provide a good editor experience for as many code editing languages as possible.

#### JSONata
JSONata tokeniser had to be written from scratch (see code-editors/monaco.js) 
JSONata autocompletion and hover providers are auto generated from existing JSONata code
One example JSONata snippet added - "randomInteger" (we can add more easily)

### z-index woes
Monaco has rich tooltips and menus - these were being clipped by the sidebar and grab handles.
I had to tweak the z-index (up or down 1 number) of side-bar/grab handle and apply a "hack" to raise the z-index of the editors form after it is shown and lower it again as it is closed (so that the slide animation continued to work correctly)
I have been dogfooding this for some time now & seems stable.
It would of course be ideal if it could be handled without programmatically raising and lowering z-index but after many many hours, it was the only solution I could get working without other compounded issues or artefacts.

### i18n
~~After several long days of trying, I have not managed to get localisation of monaco menus etc to use translations.~~
~~Hopefully you are ok with this being a "todo" item.~~
~~Promising source of info: https://github.com/blutorange/primefaces-monaco/blob/master/ESM-I18N.md however translation files appear incomplete / dated.~~
Finally manged (using primefaces-monaco as a base) to create a separate private project called monaco-editor-esm-i18n - monaco menus now localised. 

### Settings

Editor choice and settings are in editorTheme settings object. This is how I interpreted where code editor related settings are supposed to go - hopefully this is correct. 

```js
    editorTheme: {
        codeEditor: {
            lib: "monaco", //can be "monaco" or "ace"
            /** @see https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandaloneeditorconstructionoptions.html */
            options: {
                // /* theme - must be vs vs-dark or hc-black OR match the file name of a theme in 
                //  * packages/node_modules/@node-red/editor-client/src/vendor/monaco/dist/theme
                //  * e.g. "tomorrow-night", "upstream-sunburst", "github", "my-theme"
                //  */
                theme: "vs",
                minimap: {
                    enabled: true,
                    maxColumn: 40,
                    scale: 1,
                    showSlider : "mouseover",
                    renderCharacters: true
                },
                fontSize: 16,
                fontLigatures: true,
                fontFamily: "Cascadia Code, Fira Code, Consolas, 'Courier New', monospace",
                fontWeight: "300"
            },
```

NOTES: 
* I do not generate the `codeEditor` entry in settings.js if missing 
* `codeEditor` is completely optional and code editor choice defaults to `ace`
* `codeEditor.options` is completely optional and defaults in the src are set to a good level 

Additional monaco overrides are possible by suppling values in `codeEditor.options.monaco.xxx.yyy.zzz` e.g...
```js
    editorTheme: {
        codeEditor: {
            lib: "monaco", //can be "monaco" or "ace"
            options: {},
            monaco: {
                languages: {
                    typescript: {
                        javascriptDefaults: {
                            /** @see https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.typescript.languageservicedefaults.html#setcompileroptions */
                            compilerOptions: {
                                target: "ESNext",
                                allowNonTsExtensions: true,
                                checkJs: true,
                                allowJs: true,
                                noUnusedLocals: true
                            },
                            /** @see https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.typescript.languageservicedefaults.html#setdiagnosticsoptions */
                            diagnosticsOptions: {
                                diagnosticCodesToIgnore: [
                                    1108,  //return not inside function
                                    2304,  //Cannot find name 
                                    2307,  //Cannot find module 'xxx' or its corresponding type declarations 
                                    2322,  //Type 'unknown' is not assignable to type 'string'
                                    2339,  //property does not exist on xx
                                    80001, //Convert to ES6 module  
                                    80004, //JSDoc types may be moved to TypeScript types.
                                ]
                            }
                        },
                    },
                },
            }
        },
    }
```

### Integration / scr structure
* The signature of `RED.editor.createEditor(options)` remains unchanged inside of `packages/node_modules/@node-red/editor-client/src/js/ui/editor.js`  however it now calls out to `RED.editor.codeEditor.create(options);` 
* Functionality of `createEditor` is now stripped out of `packages/node_modules/@node-red/editor-client/src/js/ui/editors/editor.js` and moved to `packages/node_modules/@node-red/editor-client/src/js/ui/editors/code-editor.js`
* the creation of ace editor is now in `packages/node_modules/@node-red/editor-client/src/js/ui/editors/code-editors/ace.js`
* the creation of monaco editor is now in `packages/node_modules/@node-red/editor-client/src/js/ui/editors/code-editors/monaco.js`
* the export signature of the above 2 files `/code-editors/ace.js` and `/code-editors/monaco.js` are identical - hopefully simplifying future code editor changes

### typings
* node-red types are saved in the src tree & should be updated with changes to the function node and util class. 
   * These are in `packages/node_modules/@node-red/editor-client/src/types/node-red/*`
   * Grunt copies these to be served in `public/types/node-red/*` (as opposed to `public/vendor/monaco/types/**`) The logic for this was a future editor (or even ace) can make use of them
* default node-js types are saved in the src tree `packages/node_modules/@node-red/editor-client/src/types/node/*`
   * only `globals.d.ts` is present by default (24kb) and provides most of the nodejs intellisense (console, Buffer, setTimeout etc)
   * Grunt copies this to be served in `/types/node/*` (as opposed to `vendor/monaco/types/**`) The logic for this was a future editor (or even ace) can make use of them
   * This final commit places the most common V14.14.43 d.ts files have been included (minimised) to provide a good OOB experience for users
   

---

Let me know if you need any changes making or need any additional info.

Cheers, Steve.

_PS: As time is of the essence, much of the above is snipped from the original PR (and may contain inaccuracies - sorry)_

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
Hi Nick, I added some basic default settings in settings.js (feel free to add/remove as you see fit).

I have also updated to latest dev version (a user on the forum tried out the monaco2 branch but got hit with that i18n issue you fixed)

A few other tweaks to clean up the code and handle a known issue with monaco

But that _should_ be  it (unless I find any other problems) 

Cheers.

**Comment by Steve-Mcl** [comment]
Slight update Nick (hopefully the last). 
An issue was pointed out on the forum by a tester & I have handled it.

**Comment by Steve-Mcl** [comment]
I have been manually going through as many built in and contrib nodes as I know of which create an editor in their edit dialog. 

@dceejay @knolleary Can you think of any more nodes I should try?

### summary
* All nodes load ok, some with quirks, some accessing ace directly. 
* Mostly, contrib nodes (and a couple built in) dont call destroy and to avoid a memory leak, I listen to RED.events.on("editor:close") to clean up orphaned editor models.
* Occasionally, some nodes call directly to ACE to create their editor.

### details

#### working properly
* comment
* template
* function
* change/switch/other->Buffer 
* change/switch/other->json - not destroying editor [fixed in monaco2](https://github.com/Steve-Mcl/node-red/commit/251dda36529f1f8e62458a0e8b025dcc9c08ef6c)
* change/switch/other->jsonata - not destroying editor [fixed in monaco2](https://github.com/Steve-Mcl/node-red/commit/251dda36529f1f8e62458a0e8b025dcc9c08ef6c)
* ui-template
* uibuilder
* unsafe-function
* mssql-plus
* node-red-contrib-modbus - the flex server node has 6 JS editors in tabs - all working
* node-red-contrib-ui-svg - added support for ace function `setFontSize(number)`


#### working with minor quirks
* node-red-contrib-java-function - loads monaco but model is not set to java (no syntax colouring)
* node-red-contrib-python-function - loads ace since it calls directly to ace lib to build the editor (should call createEditor())
* node-red-contrib-influxdb - loads monaco but not settings SQL mode (same issue in ACE)
* node-red-contrib-sqlstring - loads monaco but does not explicitly destroy editor (gets mopped up in monaco.js by `RED.events.on("editor:close")`)
* node-red-contrib-postgrestor-next - loads monaco but does not explicitly destroy editor (gets mopped up in monaco.js by `RED.events.on("editor:close")`)

---

Regarding the quirky contrib nodes, once monaco is enabled, I can follow up and raise issues on these?

**Comment by knolleary** [comment]
And its merged!

Thanks for all your hard work on this @Steve-Mcl - it really is appreciated.

A couple bits to mop up - one being the private repo you reference for building monaco. Want to make sure that's more widely available. I also note there's 0.24 of monaco now available.

**Comment by Steve-Mcl** [comment]
@knolleary 

Good stuff. 


I still have a bit tidy up to do on the private repo but I hope to get that pushed later this week after pushing the mqtt-control PR which is coming along really nicely.

**Comment by Steve-Mcl** [comment]
@knolleary I have published the monaco build package (private repo) to https://github.com/Steve-Mcl/monaco-editor-esm-i18n.git and added you as collaborator. I dont know if the invite expires so please accept to permit access / collaboration rights. 
Do I need to add others?

**Comment by knolleary** [comment]
Ideally it needs to be publicly available so that anyone is able to reproduce it. It may make sense to migrate it to the `node-red` org so its properly owned by the project.

On another matter, it looks like it doesn't know about the `env` built-in we have:

image

**Comment by Steve-Mcl** [comment]
Hi Missed that one (bah) - I'll sort it. I'll also update Monaco to latest. Will raise a PR today against DEV branch.

**Comment by knolleary** [comment]
@Steve-Mcl if possible, can you do them as separate PRs? Would like to have a clean PR that shows what is needed to update Monaco without any other changes alongside it.

**Comment by Steve-Mcl** [comment]
Hi @knolleary 

Do you mean a separate PR for monaco-editor upgrade (to v0.24.0 [latest]) - and another for the node-red typedefs update (for env.get() definition)?

OR

A new single PR (i.e. not this branch) that has the editor updates & typing's in one. (which is what had planned to do)

**Comment by knolleary** [comment]
Given the choice, I would prefer two PRs:

1. to update monaco
2. to fix the typedefs

That way we have two clean reference PRs for how to do both of those tasks. It's a bit more work, but I think it will be helpful for future us when we have to do similar tasks in the future.

**Comment by Steve-Mcl** [comment]
> Given the choice, I would prefer two PRs 

NP

Will raise soon.

**Comment by Steve-Mcl** [comment]
Hi Nick, added PRs #3007 and  #3008

**Comment by Steve-Mcl** [comment]
> It may make sense to migrate it to the node-red org so its properly owned by the project

By all means. Not sure how to do that mind.

**Pull request merged**
