### PR TITLE
German I18n adjustments

### PR DESCRIPTION
**Pull request by Curvel**
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

A few German translations don't sound good at the moment. This PR changes them.
Changes were discussed in Slack channel "i18n-de".

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by beevelop** [comment]
LGTM

**Comment by nero408** [comment]
Looks good! 👏

**Comment by abrkir** [comment]
GREAT!  :)

**Comment by bastian1993** [comment]
Sounds much better! Good Job

**Comment by daniel-vera-g** [comment]
Makes sense :top:

**Comment by kuema** [comment]
Ausgezeichnet! :smile:

**Comment by knolleary** [comment]
Thanks everyone for the contribution!

**Pull request merged**
