### PR TITLE
Add Russian Locale

### PR DESCRIPTION
**Pull request by alexk111**
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes

Adds Russian Locale for:
- Editor (UI, JSONata, tips)
- Runtime
- Core nodes (messages, help files)

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

Only `.json` and `.html` files are added/updated, so no unit tests needed here.

### CODE REVIEW

**Comment by alexk111** [comment]
Clabot states "CLA: not signed yet", however it does. When I click the badge it opens the CLA page with "You have signed the CLA for node-red/node-red" at the top.

**Comment by hardillb** [comment]
The usual reasons for this is that  the commits have an email address that is not linked to your github account.

**Comment by alexk111** [comment]
What are the options to fix it? I use GitHub's `@users.noreply.github.com` no-reply email for commits and for signing CLA I used a private email.

**Comment by hardillb** [comment]
You can add multiple email addresses to your github account and the commits can be signed by any of them, but I think they have to be real (so they can be verified). So I suggest you create a disposable gmail (or similar) email address, add it to your github account then update the commits.

Also you can use the rebase (iirc) command to 

 1. compress all the commits into one
 2. change the email address on that commit

Then use a `--force` push to update your fork and it should be reflected here.

**Comment by alexk111** [comment]
@hardillb Thanks! Squashed all commits into one and updated the email.

**Comment by knolleary** [comment]
Thanks @alexk111 

Has anyone else reviewed these translations? We don't have the ability to do that ourselves, for obvious reasons.

**Comment by alexk111** [comment]
@knolleary I mentioned the PR [here](https://discourse.nodered.org/t/russian-language-translation/21280). Maybe the topic starter or someone else will review it. I'm also working on a custom NR distro for Russian-speaking users. Hopefully this will bring some feedback on the text quality :)

**Comment by knolleary** [comment]
@alexk111 well, if you know any other native Russian-speakers who wouldn't mind reading through just to spot any typos, that would help. I will add a comment to the discourse thread as well.

**Comment by alexk111** [comment]
@knolleary Ok. Thanks

**Comment by alexk111** [comment]
@knolleary fyi, the locale is used in a software I made on top of node-red (botodrom.com). it's not open to a wider audience yet, but already has a few Russian-speaking beta users, so you might consider merging it.  I'll also keep the locale updated with the new features and nr/core nodes changes :)

**Comment by dceejay** [comment]
Hi - sounds good. Is there any way we can get a 2nd opinion / feedback to verify they all make sense ? Would one of your beta users like to comment here please ?

**Comment by alexk111** [comment]
They are not GH citizens and such a request will be irrelevant for them :( As soon as I find a user familiar with GH, I'll definitely ask them to leave a comment here :)

**Comment by dceejay** [comment]
hi @alexk111   I think you will need to rebase this off latest dev so we can see the actual changes again - I did ask on the discourse forum for help - https://discourse.nodered.org/t/any-russian-speaking-users/34398 - and looks like there may be some volunteers - but we need to re-tidy this up so they can see just the changes... - Thanks
(or maybe you can DM them)

**Comment by alexk111** [comment]
Hi @dceejay. Updated the locale files with the recent changes, and rebased it onto upstream/master.

**Comment by alexk111** [comment]
Squashed into one commit to simplify the review

**Comment by alexk111** [comment]
@dceejay Please confirm if checking the commit for typos would be enough? Convincing others to install another NR instance from a GH branch looks like a non trivial task.

**Comment by dceejay** [comment]
Hi yes - we just need someone other than you to read through the https://github.com/node-red/node-red/pull/2531/files looking at the ones with the translations in and to check they make sense - both spelling and correct terminology if possible.
And to either add comments or offer suggestions or say it is all ok.

**Comment by alexk111** [comment]
Ok, got it. Thanks for the clarification!

**Comment by alexk111** [comment]
https://discourse.nodered.org/t/any-russian-speaking-users/34398/4

**Comment by dceejay** [comment]
Hi @alexk11 
Finally - we get to merge it ! thanks for being so patient... Well done !

Note in 1.2.3 we did add a couple more message you will need to add - editor json file - see https://github.com/node-red/node-red/commit/2c6cda1f27b5b5bab538f2f605209768e2d6b3ef 

We will add you to the cc list to try to alert you when we make changes.

**Comment by alexk111** [comment]
Hi @dceejay 

Thanks for merging the pr! Surely will keep the locale updated.

**Comment by dceejay** [comment]
thanks  - - we are likely to push out v1.2.4 very shortly - so if you can fix that one file asap that would be great.

**Comment by alexk111** [comment]
@dceejay Done in #2761

**Pull request merged**
